/**
 * Remove the previous browser-page build from `docs/`, and nothing else.
 *
 * WHY A SCRIPT AND NOT `--emptyOutDir`. The vite output directory is
 * `docs/`, which GitHub Pages serves whole: the built editor and demos sit
 * beside the hand-written landing page, the manual, the generated catalogs,
 * the thumbnails and the logo. Emptying that directory would delete the
 * site in order to publish the site, so `vite.config.ts` sets
 * `emptyOutDir: false` and this runs first instead.
 *
 * WHY A LIST AND NOT A DERIVATION. It is tempting to read the entries out
 * of `vite.config.ts` and delete those. But the thing that actually
 * accumulates is `assets/` — hashed chunk names, one new set per build,
 * and no entry in the config names it. So the honest form is the list
 * below, kept in step by hand, with the config's `rollupOptions.input`
 * next to it in review whenever a page is added.
 *
 * A DELETION IS NOT A MOVE. Anything under these three paths is build
 * output and can be regenerated by the command that failed to find it.
 * Nothing hand-written may ever be put inside them.
 */
import { existsSync, rmSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));

/** Every directory `npm run examples:pages` writes into `docs/`. */
const OWNED = [
  // `build.assetsDir` — the hashed JS and CSS every page shares.
  "assets",
  // One per `rollupOptions.input` entry, at the path its source has in the
  // repository, because vite roots at the repository root.
  "editor",
  "demos",
];

const removed = [];
for (const name of OWNED) {
  const path = join(ROOT, "docs", name);
  if (!existsSync(path)) continue;
  rmSync(path, { recursive: true, force: true });
  removed.push(name);
}

console.log(
  removed.length > 0
    ? `clean-pages: removed docs/{${removed.join(",")}}`
    : "clean-pages: nothing to remove",
);
