/**
 * WGSL apply-kernel codegen for device-resident runs: for each resident
 * node kind, the kernel that applies the node's semantics to the
 * resident attribute buffers, given its already-materialized field
 * columns. Codegen only — nothing here touches a device.
 *
 * Semantics are ported from the CPU node sources (`src/nodes/attributes.ts`
 * `setAttribute` numeric mode; `src/nodes/pointOps.ts` transformPoints /
 * jitterPoints / orientAlongVector loops and `src/nodes/util.ts`
 * quaternion math), which remain the bit-exact reference:
 *
 * - setAttribute stores are bit-exact for same-type f32/i32/u32 columns
 *   (raw copies) and for in-range integer conversions; out-of-range or
 *   NaN float→int stores differ (JS ToInt32/ToUint32 wraps, WGSL
 *   saturates) — GIGO class, same as the phase-20 lattice-wrap lines.
 * - jitterPoints reproduces the `hashFloat(hashCombine(seed, i, k))`
 *   chain bit-for-bit (u32 hash + exact-in-f32 hashFloat); the final
 *   `* 2 - 1`, amount multiply, and accumulate round in f32 where the
 *   CPU rounds once from f64 — tolerance class.
 * - transformPoints / orientAlongVector float math computes in f32
 *   (quaternion construction, basis branches) where the CPU computes in
 *   f64 and stores f32. Two further divergences beyond that width gap:
 *   `pcg_rotate_vec` re-associates the CPU's `A + B - C` into
 *   `A + (B - C)` via WGSL `cross`, and `cross`/`dot` may contract into
 *   FMA where the CPU's explicit expressions cannot — both shift the
 *   last ulps independently of f32-vs-f64. Branchy paths (quatFromBasis
 *   trace branches, up-parallel fallbacks) can flip at knife-edge inputs
 *   within tolerance; the baked parallel epsilon is the nearest f32 to
 *   1e-12 (9.99999996e-13, strictly below the CPU's f64 1e-12), so the
 *   fallback branch set differs by slightly more than rounding alone.
 *   orientAlongVector's zero-direction test can additionally flip for
 *   subnormal direction magnitudes (f32 squares flush to zero where f64
 *   keeps them) — subnormal GIGO class.
 *
 * Aliasing: apply kernels access only element `i`'s slots of any buffer
 * (never cross-element), param columns are separate buffers materialized
 * before the apply dispatch, and chunked dispatches partition the
 * element range exactly — so read_write attribute buffers are raced by
 * nothing.
 */
import type { GpuScalarType } from "./types.js";
import { libClosure, wgslF32 } from "./wgslLib.js";

/** 1D workgroup size every apply kernel dispatches with. */
export const APPLY_WORKGROUP_SIZE = 64;

/**
 * Apply-kernel codegen version folded into specialization keys. Bump
 * whenever emitted WGSL text changes; when the change can alter
 * produced bytes, ALSO bump the evaluator's `SALT_VERSION` so memo
 * caches never serve stale fused output.
 */
const APPLY_VERSION = "apply1";

/** Shape of a bound field column (the producing kernel's output). */
export interface ApplyColRef {
  readonly type: GpuScalarType;
  readonly tupleSize: number;
}

/** One storage binding of an apply kernel, in binding-index order. */
export interface ApplyBinding {
  readonly binding: number;
  /** Kind-specific role the planner maps to a buffer (see each maker). */
  readonly role: string;
  readonly access: "read" | "read_write";
}

/** A generated apply kernel (uniforms are always binding 0, PcgParams). */
export interface ApplyKernel {
  readonly wgsl: string;
  readonly entryPoint: "main";
  readonly workgroupSize: number;
  readonly bindings: readonly ApplyBinding[];
  /** Stable specialization key (pipeline cache). */
  readonly key: string;
}

/** Read component k of column var `v`, broadcasting scalars, as f32. */
function colReadF32(v: string, col: ApplyColRef, k: number): string {
  const e = colReadRaw(v, col, k);
  return col.type === "f32" ? e : `f32(${e})`;
}

/** Raw (unconverted) component read with scalar broadcast. */
function colReadRaw(v: string, col: ApplyColRef, k: number): string {
  if (col.tupleSize === 1) return `${v}[i]`;
  return k === 0 ? `${v}[i * ${col.tupleSize}u]` : `${v}[i * ${col.tupleSize}u + ${k}u]`;
}

function flatIdx(v: string, ts: number, k: number): string {
  if (ts === 1) return `${v}[i]`;
  return k === 0 ? `${v}[i * ${ts}u]` : `${v}[i * ${ts}u + ${k}u]`;
}

function assemble(
  kindKey: string,
  bindings: readonly { role: string; access: "read" | "read_write"; elem: GpuScalarType; comment: string }[],
  helpers: readonly string[],
  body: string,
): ApplyKernel {
  const decls: string[] = ["@group(0) @binding(0) var<uniform> params: PcgParams;"];
  const out: ApplyBinding[] = [];
  bindings.forEach((b, i) => {
    const binding = i + 1;
    const access = b.access === "read" ? "read" : "read_write";
    decls.push(
      `@group(0) @binding(${binding}) var<storage, ${access}> b${binding}: array<${b.elem}>; // ${b.comment}`,
    );
    out.push({ binding, role: b.role, access: b.access });
  });
  const wgsl = `// Generated by pcg-ts resident-run apply codegen.
// Dispatch: 1D, chunked; element index i = chunkOffset + gid.x, one
// invocation per element; only element i's slots are accessed.

struct PcgParams {
  count: u32,
  seed: u32,
  chunkOffset: u32,
}

${decls.join("\n")}

${helpers.length > 0 ? `${helpers.join("\n\n")}\n\n` : ""}@compute @workgroup_size(${APPLY_WORKGROUP_SIZE})
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x + params.chunkOffset;
  if (i >= params.count) {
    return;
  }
${body}
}
`;
  return {
    wgsl,
    entryPoint: "main",
    workgroupSize: APPLY_WORKGROUP_SIZE,
    bindings: out,
    key: `${APPLY_VERSION}|${kindKey}`,
  };
}

const colKey = (c: ApplyColRef): string => `${c.type}x${c.tupleSize}`;

// ---------------------------------------------------------------------------
// setAttribute (numeric mode): store the field column into the target.
// Roles: "value" (the column), "target" (the attribute being written).

/**
 * Store conversions mirror the CPU typed-array stores: same-type f32
 * copies move raw bits (u32-bound buffers) so the pure hash chain stays
 * bit-exact and subnormals survive; integer↔integer conversions use
 * bitcast (the modular ToInt32/ToUint32 semantics); float→int uses the
 * WGSL conversion (in-range truncation identical; out-of-range/NaN is
 * GIGO — see the module doc); bool stores nonzero as 1 (NaN != 0 is
 * true in both).
 */
export function makeSetAttributeApply(
  col: ApplyColRef,
  targetType: "f32" | "i32" | "u32" | "bool",
  tupleSize: number,
): ApplyKernel {
  // Bind element types: bool targets are u32 0/1 buffers; the bit-exact
  // f32→f32 copy binds both sides as u32. The raw u32 copy is in fact
  // *more* bit-preserving than the CPU store, which canonicalizes
  // non-canonical NaN payloads on the way through a Float32Array.
  const rawF32Copy = targetType === "f32" && col.type === "f32";
  const colElem: GpuScalarType = rawF32Copy ? "u32" : col.type;
  const outElem: GpuScalarType = targetType === "bool" || rawF32Copy ? "u32" : targetType;
  const boundCol: ApplyColRef = { type: colElem, tupleSize: col.tupleSize };
  const conv = (raw: string, f32: string): string => {
    switch (targetType) {
      case "f32":
        return rawF32Copy ? raw : f32; // f32(int) matches fround(Number(v))
      case "i32":
        return col.type === "f32" ? `i32(${raw})` : col.type === "i32" ? raw : `bitcast<i32>(${raw})`;
      case "u32":
        return col.type === "f32" ? `u32(${raw})` : col.type === "u32" ? raw : `bitcast<u32>(${raw})`;
      default: {
        const zero = col.type === "f32" ? "0f" : col.type === "i32" ? "0i" : "0u";
        return `select(0u, 1u, ${raw} != ${zero})`;
      }
    }
  };
  const lines: string[] = [];
  for (let k = 0; k < tupleSize; k++) {
    const raw = colReadRaw("b1", boundCol, k);
    lines.push(`  ${flatIdx("b2", tupleSize, k)} = ${conv(raw, colReadF32("b1", boundCol, k))};`);
  }
  return assemble(
    `setAttribute|col=${colKey(col)}|out=${targetType}x${tupleSize}`,
    [
      { role: "value", access: "read", elem: colElem, comment: `value column ${colKey(col)}` },
      { role: "target", access: "read_write", elem: outElem, comment: `target attribute ${targetType} tupleSize ${tupleSize}` },
    ],
    [],
    lines.join("\n"),
  );
}

// ---------------------------------------------------------------------------
// quaternion helpers shared by transformPoints / orientAlongVector,
// ported from src/nodes/util.ts (same formulas and branch structure).

const QUAT_HELPERS: Record<string, string> = {
  // quatFromEulerDeg: extrinsic XYZ (R = Rz * Ry * Rx), degrees.
  euler: `fn pcg_quat_from_euler_deg(r: vec3<f32>) -> vec4<f32> {
  let h = r * ${wgslF32(Math.PI / 360, "internal PI/360")};
  let sx = sin(h.x);
  let cx = cos(h.x);
  let sy = sin(h.y);
  let cy = cos(h.y);
  let sz = sin(h.z);
  let cz = cos(h.z);
  return vec4<f32>(
    sx * cy * cz - cx * sy * sz,
    cx * sy * cz + sx * cy * sz,
    cx * cy * sz - sx * sy * cz,
    cx * cy * cz + sx * sy * sz);
}`,
  mul: `fn pcg_quat_mul(a: vec4<f32>, b: vec4<f32>) -> vec4<f32> {
  return vec4<f32>(
    a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
    a.w * b.y - a.x * b.z + a.y * b.w + a.z * b.x,
    a.w * b.z + a.x * b.y - a.y * b.x + a.z * b.w,
    a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z);
}`,
  rotate: `fn pcg_rotate_vec(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
  let t = 2f * cross(q.xyz, v);
  return v + q.w * t + cross(q.xyz, t);
}`,
  // quatFromBasis: three.js setFromRotationMatrix trace branches.
  basis: `fn pcg_quat_from_basis(bx: vec3<f32>, by: vec3<f32>, bz: vec3<f32>) -> vec4<f32> {
  let m11 = bx.x;
  let m12 = by.x;
  let m13 = bz.x;
  let m21 = bx.y;
  let m22 = by.y;
  let m23 = bz.y;
  let m31 = bx.z;
  let m32 = by.z;
  let m33 = bz.z;
  let trace = m11 + m22 + m33;
  if (trace > 0f) {
    let s = 0.5f / sqrt(trace + 1f);
    return vec4<f32>((m32 - m23) * s, (m13 - m31) * s, (m21 - m12) * s, 0.25f / s);
  } else if (m11 > m22 && m11 > m33) {
    let s = 2f * sqrt(1f + m11 - m22 - m33);
    return vec4<f32>(0.25f * s, (m12 + m21) / s, (m13 + m31) / s, (m32 - m23) / s);
  } else if (m22 > m33) {
    let s = 2f * sqrt(1f + m22 - m11 - m33);
    return vec4<f32>((m12 + m21) / s, 0.25f * s, (m23 + m32) / s, (m13 - m31) / s);
  }
  let s = 2f * sqrt(1f + m33 - m11 - m22);
  return vec4<f32>((m13 + m31) / s, (m23 + m32) / s, 0.25f * s, (m21 - m12) / s);
}`,
};

// ---------------------------------------------------------------------------
// transformPoints: P' = R * (scale * P) + translate, composing with
// existing rot (quaternion product) / scale (componentwise) attributes.
// Roles: "translate", "rotateEuler", "scale" (columns), "P", then
// "rot" / "scaleAttr" when composed (all f32 buffers).

export function makeTransformPointsApply(
  translate: ApplyColRef,
  rotateEuler: ApplyColRef,
  scale: ApplyColRef,
  hasRot: boolean,
  hasScale: boolean,
): ApplyKernel {
  const bindings: { role: string; access: "read" | "read_write"; elem: GpuScalarType; comment: string }[] = [
    { role: "translate", access: "read", elem: translate.type, comment: `translate column ${colKey(translate)}` },
    { role: "rotateEuler", access: "read", elem: rotateEuler.type, comment: `rotateEuler column ${colKey(rotateEuler)}` },
    { role: "scale", access: "read", elem: scale.type, comment: `scale column ${colKey(scale)}` },
    { role: "P", access: "read_write", elem: "f32", comment: "attribute P: f32 tupleSize 3" },
  ];
  let next = 5;
  let rotVar = "";
  let sclVar = "";
  if (hasRot) {
    rotVar = `b${next++}`;
    bindings.push({ role: "rot", access: "read_write", elem: "f32", comment: "attribute rot: f32 tupleSize 4" });
  }
  if (hasScale) {
    sclVar = `b${next++}`;
    bindings.push({ role: "scaleAttr", access: "read_write", elem: "f32", comment: "attribute scale: f32 tupleSize 3" });
  }
  const lines: string[] = [];
  lines.push(`  let s = vec3<f32>(${[0, 1, 2].map((k) => colReadF32("b3", scale, k)).join(", ")});`);
  lines.push(`  let q = pcg_quat_from_euler_deg(vec3<f32>(${[0, 1, 2].map((k) => colReadF32("b2", rotateEuler, k)).join(", ")}));`);
  lines.push(`  let v = pcg_rotate_vec(q, vec3<f32>(b4[i * 3u] * s.x, b4[i * 3u + 1u] * s.y, b4[i * 3u + 2u] * s.z));`);
  lines.push(`  b4[i * 3u] = v.x + ${colReadF32("b1", translate, 0)};`);
  lines.push(`  b4[i * 3u + 1u] = v.y + ${colReadF32("b1", translate, 1)};`);
  lines.push(`  b4[i * 3u + 2u] = v.z + ${colReadF32("b1", translate, 2)};`);
  if (hasRot) {
    lines.push(`  let q2 = pcg_quat_mul(q, vec4<f32>(${rotVar}[i * 4u], ${rotVar}[i * 4u + 1u], ${rotVar}[i * 4u + 2u], ${rotVar}[i * 4u + 3u]));`);
    lines.push(`  ${rotVar}[i * 4u] = q2.x;`);
    lines.push(`  ${rotVar}[i * 4u + 1u] = q2.y;`);
    lines.push(`  ${rotVar}[i * 4u + 2u] = q2.z;`);
    lines.push(`  ${rotVar}[i * 4u + 3u] = q2.w;`);
  }
  if (hasScale) {
    lines.push(`  ${sclVar}[i * 3u] = ${sclVar}[i * 3u] * s.x;`);
    lines.push(`  ${sclVar}[i * 3u + 1u] = ${sclVar}[i * 3u + 1u] * s.y;`);
    lines.push(`  ${sclVar}[i * 3u + 2u] = ${sclVar}[i * 3u + 2u] * s.z;`);
  }
  return assemble(
    `transformPoints|t=${colKey(translate)}|r=${colKey(rotateEuler)}|s=${colKey(scale)}|rot=${hasRot ? 1 : 0}|scl=${hasScale ? 1 : 0}`,
    bindings,
    [QUAT_HELPERS.euler, QUAT_HELPERS.mul, QUAT_HELPERS.rotate],
    lines.join("\n"),
  );
}

// ---------------------------------------------------------------------------
// jitterPoints: P[i][k] += (hashFloat(hashCombine(seed, i, k)) * 2 - 1)
// * amount[i][k]. Roles: "amount" (column), "P". The seed uniform is the
// node's jitter-combined seed; CPU `hashCombine(seed, i, k)` is exactly
// the library's `pcg_hash3` (both chain hashSeed(3) through the same
// murmur rounds) — bit-exact, pinned by the device parity suite.

export function makeJitterPointsApply(amount: ApplyColRef): ApplyKernel {
  const lines: string[] = [];
  for (let k = 0; k < 3; k++) {
    const idx = k === 0 ? "i * 3u" : `i * 3u + ${k}u`;
    lines.push(
      `  b2[${idx}] = b2[${idx}] + (pcg_hash_float(pcg_hash3(params.seed, i, ${k}u)) * 2f - 1f) * ${colReadF32("b1", amount, k)};`,
    );
  }
  return assemble(
    `jitterPoints|a=${colKey(amount)}`,
    [
      { role: "amount", access: "read", elem: amount.type, comment: `amount column ${colKey(amount)}` },
      { role: "P", access: "read_write", elem: "f32", comment: "attribute P: f32 tupleSize 3" },
    ],
    libClosure(["pcg_hash3", "pcg_hash_float"]),
    lines.join("\n"),
  );
}

// ---------------------------------------------------------------------------
// orientAlongVector: build rot quaternions pointing `axis` along the
// direction column, up hint fixing roll, with the CPU's fallback and
// keep-prior-rot-on-zero-direction semantics. Roles: "direction"
// (column), "rot" (read_write; prior values pre-loaded so skipped
// lanes keep them). The axis and the f64-normalized up are baked.

const ORIENT_BASIS_ARGS: Record<string, string> = {
  "+x": "f, u, -r",
  "-x": "-f, u, r",
  "+y": "-r, f, u",
  "-y": "r, -f, u",
  "+z": "r, u, f",
  "-z": "-r, u, -f",
};

export function makeOrientApply(
  direction: ApplyColRef,
  axis: "+x" | "-x" | "+y" | "-y" | "+z" | "-z",
  up: readonly [number, number, number],
): ApplyKernel {
  // Normalize the up hint in f64 exactly as the CPU does, then bake the
  // f32-rounded components (single rounding).
  const upLenSq = up[0] * up[0] + up[1] * up[1] + up[2] * up[2];
  const upInv = upLenSq > 0 ? 1 / Math.sqrt(upLenSq) : 0;
  const upLit = (k: number): string => wgslF32(up[k] * upInv, "orientAlongVector up");
  const eps = wgslF32(1e-12, "internal ORIENT_PARALLEL_EPS");
  const body = `  let d = vec3<f32>(${[0, 1, 2].map((k) => colReadF32("b1", direction, k)).join(", ")});
  let dl = dot(d, d);
  if (dl == 0f) {
    return; // zero direction: keep the prior rot
  }
  let f = d * (1f / sqrt(dl));
  let up = vec3<f32>(${upLit(0)}, ${upLit(1)}, ${upLit(2)});
  // right = up x forward, falling back when (anti)parallel.
  var r = cross(up, f);
  var rl = dot(r, r);
  if (rl <= ${eps}) {
    // [0, 0, 1] x f
    r = vec3<f32>(-f.y, f.x, 0f);
    rl = r.x * r.x + r.y * r.y;
    if (rl <= ${eps}) {
      // f is (anti)parallel to Z too; [1, 0, 0] x f always works here.
      r = vec3<f32>(0f, -f.z, f.y);
      rl = r.y * r.y + r.z * r.z;
    }
  }
  r = r * (1f / sqrt(rl));
  // u = forward x right (unit: forward and right are orthonormal).
  let u = cross(f, r);
  let q = pcg_quat_from_basis(${ORIENT_BASIS_ARGS[axis]});
  b2[i * 4u] = q.x;
  b2[i * 4u + 1u] = q.y;
  b2[i * 4u + 2u] = q.z;
  b2[i * 4u + 3u] = q.w;`;
  return assemble(
    `orientAlongVector|d=${colKey(direction)}|axis=${axis}|up=${[0, 1, 2].map(upLit).join(",")}`,
    [
      { role: "direction", access: "read", elem: direction.type, comment: `direction column ${colKey(direction)}` },
      { role: "rot", access: "read_write", elem: "f32", comment: "attribute rot: f32 tupleSize 4" },
    ],
    [QUAT_HELPERS.basis],
    body,
  );
}
