import { describe, expect, it } from "vitest";
import { makeField } from "../fields/index.js";
import { peekFieldSpec } from "../fields/spec.js";
import { type FieldSpec, type FieldSpecArg, fieldFromJson, listFieldFns } from "../fields/fieldJson.js";
import { paramConstValues } from "./compile.js";
import { compileFieldSpec, supportedGpuFieldFns } from "./index.js";
import type { FieldKernelLayout } from "./index.js";

const LAYOUT: FieldKernelLayout = {
  attributes: {
    P: { type: "f32", tupleSize: 3 },
    density: { type: "f32", tupleSize: 1 },
    uv: { type: "f32", tupleSize: 2 },
    active: { type: "bool", tupleSize: 1 },
    id: { type: "u32", tupleSize: 1 },
    material: { type: "i32", tupleSize: 1 },
  },
};

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

describe("compileFieldSpec goldens", () => {
  it("constant scalar kernel", () => {
    const k = compileFieldSpec({ fn: "constant", value: 2 }, LAYOUT);
    expect(k.wgsl).toBe(`// Generated by pcg-ts compileFieldSpec (WGSL field kernel).
// Dispatch: 1D, chunked; each chunk runs ceil(chunkElements / 64) workgroups of 64
// with element index i = chunkOffset + gid.x; one invocation per element.

struct PcgParams {
  count: u32,
  seed: u32,
  chunkOffset: u32,
}

@group(0) @binding(0) var<uniform> params: PcgParams;
@group(0) @binding(1) var<storage, read_write> outBuf: array<f32>;

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x + params.chunkOffset;
  if (i >= params.count) {
    return;
  }
  let v0 = 2f;
  outBuf[i] = v0;
}
`);
    expect(k.entryPoint).toBe("main");
    expect(k.workgroupSize).toBe(64);
    expect(k.outType).toBe("f32");
    expect(k.outTupleSize).toBe(1);
    expect(k.inputs).toEqual([]);
    expect(k.bindings).toEqual({ uniforms: 0, output: 1 });
    expect(k.usesSeed).toBe(false);
  });

  it("nodeSeed kernel: the seed uniform, split so both sides land on one f32", () => {
    const k = compileFieldSpec({ fn: "nodeSeed" }, LAYOUT);
    // The whole body, so a future edit to the split has to be deliberate.
    // `seed >> 8` is under 2^24 and converts exactly; `* 256.0` only
    // moves the exponent; the single add is correctly rounded. So this
    // is `Math.fround(seed)` — what the CPU's Float32Array store
    // produces — without depending on how an adapter rounds a lossy
    // u32-to-f32 conversion, which for a hashed node seed is every
    // value rather than an edge case.
    expect(k.wgsl).toContain(
      "  let v0 = f32(params.seed >> 8u) * 256.0 + f32(params.seed & 0xFFu);\n  outBuf[i] = v0;",
    );
    expect(k.usesSeed).toBe(true);
    expect(k.outType).toBe("f32");
    expect(k.outTupleSize).toBe(1);
    // No storage buffer, no const slot, bare 12-byte header: the seed is
    // a uniform member every kernel already carries.
    expect(k.inputs).toEqual([]);
    expect(k.constSlots).toBe(0);
    expect(k.paramNames).toEqual([]);
    expect(k.uniformBytes).toBe(12);
  });

  it("a nodeSeed kernel reads the seed, it does not bake it", () => {
    // The two-keys hazard `param` documented, arriving as a value that
    // moves on every drag of a seed box. What keeps it away here is that
    // the seed is READ from the uniform the dispatch writes rather than
    // emitted as a literal — so the WGSL, and therefore `kernel.key`, is
    // the same text for every seed and one pipeline serves them all.
    // (`compileFieldSpec` is never handed a seed at all, which is the
    // structural half of the same statement; the per-seed cache count is
    // asserted end to end in `resolver.test.ts`.)
    const k = compileFieldSpec({ fn: "nodeSeed" }, LAYOUT);
    // Every occurrence of the seed in the body is a uniform read.
    expect(count(k.wgsl, "params.seed")).toBe(2);
    // The uniform member is declared, not a value substituted for it.
    expect(k.wgsl).toContain("  seed: u32,");
    expect(k.key).toContain("spec=nodeSeed");
    // The layout offers attributes; a seed-only kernel binds none of
    // them, so nothing about the geometry can enter the key either.
    expect(k.key).toContain("layout=[]");
  });

  it("attribute * randomField kernel (hash library, seed uniform)", () => {
    const k = compileFieldSpec(
      { fn: "mul", args: [{ fn: "attribute", name: "density" }, { fn: "randomField", key: "jitter" }] },
      LAYOUT,
    );
    expect(k.wgsl).toBe(`// Generated by pcg-ts compileFieldSpec (WGSL field kernel).
// Dispatch: 1D, chunked; each chunk runs ceil(chunkElements / 64) workgroups of 64
// with element index i = chunkOffset + gid.x; one invocation per element.

struct PcgParams {
  count: u32,
  seed: u32,
  chunkOffset: u32,
}

@group(0) @binding(0) var<uniform> params: PcgParams;
@group(0) @binding(1) var<storage, read> in0: array<f32>; // attribute "P": f32 tupleSize 3
@group(0) @binding(2) var<storage, read> in1: array<f32>; // attribute "density": f32 tupleSize 1
@group(0) @binding(3) var<storage, read_write> outBuf: array<f32>;

fn pcg_hash_mix(h_in: u32, value: u32) -> u32 {
  var k = value * 0xcc9e2d51u;
  k = (k << 15u) | (k >> 17u);
  k = k * 0x1b873593u;
  var h = h_in ^ k;
  h = (h << 13u) | (h >> 19u);
  h = h * 5u + 0xe6546b64u;
  return h;
}

fn pcg_hash_finalize(h_in: u32) -> u32 {
  var h = h_in ^ (h_in >> 16u);
  h = h * 0x85ebca6bu;
  h = h ^ (h >> 13u);
  h = h * 0xc2b2ae35u;
  h = h ^ (h >> 16u);
  return h;
}

fn pcg_hash3(a: u32, b: u32, c: u32) -> u32 {
  return pcg_hash_finalize(pcg_hash_mix(pcg_hash_mix(pcg_hash_mix(0x0ff426f8u, a), b), c));
}

fn pcg_hash4(a: u32, b: u32, c: u32, d: u32) -> u32 {
  return pcg_hash_finalize(pcg_hash_mix(pcg_hash_mix(pcg_hash_mix(pcg_hash_mix(0x89985015u, a), b), c), d));
}

fn pcg_hash_float(h: u32) -> f32 {
  return f32(h >> 8u) * 5.960464477539063e-8f;
}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x + params.chunkOffset;
  if (i >= params.count) {
    return;
  }
  let v0 = in1[i];
  let v1 = pcg_hash_float(pcg_hash3(params.seed, 0x02049853u, pcg_hash4(bitcast<u32>(in0[i * 3u]), bitcast<u32>(in0[i * 3u + 1u]), bitcast<u32>(in0[i * 3u + 2u]), 0u)));
  let v2 = v0 * v1;
  outBuf[i] = v2;
}
`);
    expect(k.usesSeed).toBe(true);
    // P rides along even though the spec never names it: randomField keys
    // on point identity, so it reads the position bits (and the `seed`
    // attribute, which this layout does not carry, so it folds in 0u).
    expect(k.inputs).toEqual([
      { name: "P", type: "f32", tupleSize: 3, binding: 1 },
      { name: "density", type: "f32", tupleSize: 1, binding: 2 },
    ]);
    expect(k.bindings).toEqual({ uniforms: 0, output: 3 });
  });

  it("ramp over length(position) kernel (per-instance helper)", () => {
    const k = compileFieldSpec(
      {
        fn: "ramp",
        args: [{ fn: "length", args: [{ fn: "position" }] }],
        stops: [
          [0, 1],
          [2, 0.5],
          [4, 0],
        ],
      },
      LAYOUT,
    );
    expect(k.wgsl).toBe(`// Generated by pcg-ts compileFieldSpec (WGSL field kernel).
// Dispatch: 1D, chunked; each chunk runs ceil(chunkElements / 64) workgroups of 64
// with element index i = chunkOffset + gid.x; one invocation per element.

struct PcgParams {
  count: u32,
  seed: u32,
  chunkOffset: u32,
}

@group(0) @binding(0) var<uniform> params: PcgParams;
@group(0) @binding(1) var<storage, read> in0: array<f32>; // attribute "P": f32 tupleSize 3
@group(0) @binding(2) var<storage, read_write> outBuf: array<f32>;

fn pcg_ramp_0(t: f32) -> f32 {
  if (t <= 0f) {
    return 1f;
  }
  if (t >= 4f) {
    return 0f;
  }
  if (t <= 2f) {
    return 1f + -0.5f * ((t - 0f) / 2f);
  }
  return 0.5f + -0.5f * ((t - 2f) / 2f);
}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x + params.chunkOffset;
  if (i >= params.count) {
    return;
  }
  let v0 = vec3<f32>(in0[i * 3u], in0[i * 3u + 1u], in0[i * 3u + 2u]);
  let v1 = dot(v0, v0);
  let v2 = sqrt(v1);
  let v3 = pcg_ramp_0(v2);
  outBuf[i] = v3;
}
`);
  });
});

describe("grammar coverage", () => {
  it("the compiler supports the complete field JSON grammar", () => {
    expect(supportedGpuFieldFns()).toEqual(listFieldFns());
  });

  const MINIMAL_SPECS: Record<string, unknown> = {
    constant: { fn: "constant", value: 1 },
    attribute: { fn: "attribute", name: "density" },
    position: { fn: "position" },
    index: { fn: "index" },
    fraction: { fn: "fraction" },
    nodeSeed: { fn: "nodeSeed" },
    randomField: { fn: "randomField" },
    // Unbound on purpose: compiling a `param` needs its name and nothing
    // else, which is exactly why it lowers to a uniform slot.
    param: { fn: "param", name: "amplitude" },
    add: { fn: "add", args: [1, 2] },
    sub: { fn: "sub", args: [1, 2] },
    mul: { fn: "mul", args: [1, 2] },
    div: { fn: "div", args: [1, 2] },
    min: { fn: "min", args: [1, 2] },
    max: { fn: "max", args: [1, 2] },
    abs: { fn: "abs", args: [-1] },
    floor: { fn: "floor", args: [1.5] },
    sin: { fn: "sin", args: [1] },
    cos: { fn: "cos", args: [1] },
    tan: { fn: "tan", args: [1] },
    asin: { fn: "asin", args: [0.5] },
    acos: { fn: "acos", args: [0.5] },
    atan: { fn: "atan", args: [1] },
    atan2: { fn: "atan2", args: [1, 2] },
    clamp: { fn: "clamp", args: [1, 0, 2] },
    lerp: { fn: "lerp", args: [0, 1, 0.5] },
    remap: { fn: "remap", args: [1, 0, 2, 0, 1] },
    select: { fn: "select", args: [1, 2, 3] },
    lt: { fn: "lt", args: [1, 2] },
    le: { fn: "le", args: [1, 2] },
    gt: { fn: "gt", args: [1, 2] },
    ge: { fn: "ge", args: [1, 2] },
    eq: { fn: "eq", args: [1, 2] },
    ne: { fn: "ne", args: [1, 2] },
    dot: { fn: "dot", args: [[1, 2, 3], [4, 5, 6]] },
    length: { fn: "length", args: [[1, 2, 3]] },
    normalize: { fn: "normalize", args: [[1, 2, 3]] },
    vec: { fn: "vec", args: [1, 2, 3] },
    component: { fn: "component", args: [[1, 2, 3]], index: 1 },
    ramp: { fn: "ramp", args: [1], stops: [[0, 0], [1, 1]] },
    valueNoise: { fn: "valueNoise" },
    perlinNoise: { fn: "perlinNoise" },
    simplexNoise: { fn: "simplexNoise" },
    worleyNoise: { fn: "worleyNoise" },
    fbm: { fn: "fbm", base: "perlinNoise" },
  };

  it("has a minimal compile case for every grammar fn", () => {
    expect(Object.keys(MINIMAL_SPECS).sort()).toEqual(listFieldFns());
  });

  for (const [fn, spec] of Object.entries(MINIMAL_SPECS)) {
    it(`compiles ${fn}`, () => {
      const k = compileFieldSpec(spec as FieldSpecArg, LAYOUT);
      expect(k.wgsl).toContain("@compute @workgroup_size(64)");
      expect(k.wgsl).toContain("outBuf[i");
    });
  }
});

describe("codegen structure", () => {
  it("emits each library function exactly once even when shared", () => {
    const k = compileFieldSpec(
      {
        fn: "add",
        args: [
          { fn: "add", args: [{ fn: "valueNoise" }, { fn: "perlinNoise" }] },
          {
            fn: "add",
            args: [
              { fn: "simplexNoise" },
              { fn: "add", args: [{ fn: "worleyNoise" }, { fn: "randomField" }] },
            ],
          },
        ],
      },
      LAYOUT,
    );
    for (const lib of [
      "fn pcg_hash_mix(",
      "fn pcg_hash_finalize(",
      "fn pcg_hash3(",
      "fn pcg_hash4(",
      "fn pcg_hash5(",
      "fn pcg_hash_float(",
      "fn pcg_fade(",
      "fn pcg_mix(",
      "fn pcg_value_noise(",
      "fn pcg_perlin_noise(",
      "fn pcg_simplex_noise(",
      "fn pcg_worley(",
      "var<private> PCG_GRAD3",
    ]) {
      expect(count(k.wgsl, lib), lib).toBe(1);
    }
  });

  it("deduplicates shared subtrees into one SSA value", () => {
    const noise = { fn: "perlinNoise", opts: { seed: 5 } };
    const k = compileFieldSpec(
      { fn: "add", args: [{ fn: "mul", args: [noise, noise] }, noise] },
      LAYOUT,
    );
    // One definition plus exactly one call — the three structurally
    // identical noise nodes share a single let.
    expect(count(k.wgsl, "pcg_perlin_noise")).toBe(2);
    expect(k.wgsl).toContain("let v3 = v2 * v2;");
    expect(k.wgsl).toContain("let v4 = v3 + v2;");
  });

  it("defaulted options compile identically to explicit defaults", () => {
    const a = compileFieldSpec({ fn: "perlinNoise" }, LAYOUT);
    const b = compileFieldSpec({ fn: "perlinNoise", opts: { seed: 0, frequency: 1 } }, LAYOUT);
    expect(b.wgsl).toBe(a.wgsl);
    expect(b.key).toBe(a.key);
  });

  it("orders input bindings by attribute name", () => {
    const k = compileFieldSpec(
      { fn: "add", args: [{ fn: "attribute", name: "density" }, { fn: "component", args: [{ fn: "attribute", name: "P" }], index: 0 }] },
      LAYOUT,
    );
    expect(k.inputs).toEqual([
      { name: "P", type: "f32", tupleSize: 3, binding: 1 },
      { name: "density", type: "f32", tupleSize: 1, binding: 2 },
    ]);
    expect(k.bindings).toEqual({ uniforms: 0, output: 3 });
  });

  it("worley output variants select the right lanes and flags", () => {
    const f1 = compileFieldSpec({ fn: "worleyNoise" }, LAYOUT);
    expect(f1.wgsl).toContain(", false, false)");
    expect(f1.wgsl).toMatch(/let v\d+ = v\d+\.x;/);
    const f2 = compileFieldSpec({ fn: "worleyNoise", opts: { output: "f2" } }, LAYOUT);
    expect(f2.wgsl).toContain(", false, true)");
    expect(f2.wgsl).toMatch(/let v\d+ = v\d+\.y;/);
    const diff = compileFieldSpec({ fn: "worleyNoise", opts: { output: "f2-f1", exact: true } }, LAYOUT);
    expect(diff.wgsl).toContain(", true, true)");
    expect(diff.wgsl).toMatch(/let v\d+ = v\d+\.y - v\d+\.x;/);
  });

  it("fbm fuses octaves into a constant-trip loop with baked chains", () => {
    const k = compileFieldSpec(
      { fn: "fbm", base: "valueNoise", opts: { seed: 7, octaves: 3, frequency: 2 } },
      LAYOUT,
    );
    expect(k.wgsl).toContain("fn pcg_fbm_0(p: vec3<f32>) -> f32 {");
    expect(k.wgsl).toContain("var seeds = array<u32, 3>(");
    expect(k.wgsl).toContain("var freqs = array<f32, 3>(2f, 4f, 8f);");
    expect(k.wgsl).toContain("var amps = array<f32, 3>(1f, 0.5f, 0.25f);");
    expect(k.wgsl).toContain("for (var o = 0u; o < 3u; o++) {");
    expect(count(k.wgsl, "pcg_fbm_0")).toBe(2); // definition + one call
  });

  it("normalized noise wraps with the CPU range endpoints", () => {
    const k = compileFieldSpec({ fn: "perlinNoise", opts: { normalized: true } }, LAYOUT);
    expect(k.wgsl).toMatch(/let v\d+ = \(v\d+ - -1f\) \/ 2f;/);
    const w = compileFieldSpec({ fn: "worleyNoise", opts: { normalized: true } }, LAYOUT);
    // f1 range is [0, sqrt(3)]; the span serializes as fround(sqrt(3)).
    expect(w.wgsl).toMatch(/let v\d+ = \(v\d+ - 0f\) \/ 1\.7320507764816284f;/);
  });

  it("fbm normalized compiles for every base with a summed range", () => {
    for (const base of ["valueNoise", "perlinNoise", "simplexNoise", "worleyNoise"]) {
      const k = compileFieldSpec({ fn: "fbm", base, opts: { octaves: 2, normalized: true } }, LAYOUT);
      expect(k.wgsl).toMatch(/let v\d+ = \(v\d+ - /);
    }
    // valueNoise raw range [0, 1] at gain 0.5, 2 octaves → [0, 1.5].
    const v = compileFieldSpec({ fn: "fbm", base: "valueNoise", opts: { octaves: 2, normalized: true } }, LAYOUT);
    expect(v.wgsl).toMatch(/let v\d+ = \(v\d+ - 0f\) \/ 1\.5f;/);
  });

  it("bool attributes bind as u32 and read as f32", () => {
    const k = compileFieldSpec({ fn: "attribute", name: "active" }, LAYOUT);
    expect(k.inputs).toEqual([{ name: "active", type: "u32", tupleSize: 1, binding: 1 }]);
    expect(k.wgsl).toContain("var<storage, read> in0: array<u32>;");
    expect(k.wgsl).toContain("let v0 = f32(in0[i]);");
    expect(k.outType).toBe("f32"); // CPU bool attribute fields evaluate to f32
  });

  it("integer attributes at the root copy raw and keep their type", () => {
    const u = compileFieldSpec({ fn: "attribute", name: "id" }, LAYOUT);
    expect(u.outType).toBe("u32");
    expect(u.wgsl).toContain("outBuf[i] = in0[i];");
    expect(u.wgsl).toContain("var<storage, read_write> outBuf: array<u32>;");
    const i = compileFieldSpec({ fn: "attribute", name: "material" }, LAYOUT);
    expect(i.outType).toBe("i32");
    expect(i.wgsl).toContain("var<storage, read_write> outBuf: array<i32>;");
  });

  it("integer attributes inside expressions convert to f32", () => {
    const k = compileFieldSpec({ fn: "add", args: [{ fn: "attribute", name: "id" }, 1] }, LAYOUT);
    expect(k.outType).toBe("f32");
    expect(k.wgsl).toContain("let v0 = f32(in0[i]);");
  });

  it("index is u32 at the root and f32 inside expressions", () => {
    const root = compileFieldSpec({ fn: "index" }, LAYOUT);
    expect(root.outType).toBe("u32");
    expect(root.wgsl).toContain("outBuf[i] = i;");
    const expr = compileFieldSpec({ fn: "mul", args: [{ fn: "index" }, 2] }, LAYOUT);
    expect(expr.outType).toBe("f32");
    expect(expr.wgsl).toContain("let v0 = f32(i);");
  });

  it("fraction divides by max(count, 2) - 1, so no lane can divide by zero", () => {
    // The guard IS the CPU's `n > 1 ? n - 1 : 1`, branch-free: at count 1
    // the lone lane computes 0/1 = 0, the same value the CPU produces,
    // and the divisor is never 0 at any count. A regression here would
    // show up as NaN on one-element domains only — the case a
    // whole-cloud parity sweep is least likely to sample.
    const k = compileFieldSpec({ fn: "fraction" }, LAYOUT);
    expect(k.outType).toBe("f32");
    expect(k.outTupleSize).toBe(1);
    expect(k.wgsl).toContain("let v0 = f32(i) / f32(max(params.count, 2u) - 1u);");
    expect(k.wgsl).toContain("outBuf[i] = v0;");
    // Unlike `index`, it is NOT a u32 root special case: the CPU column
    // is f32, so the device column must be too.
    expect(k.wgsl).toContain("var<storage, read_write> outBuf: array<f32>;");
  });

  it("broadcasts scalars against vectors by splatting", () => {
    const k = compileFieldSpec({ fn: "add", args: [{ fn: "position" }, 1] }, LAYOUT);
    expect(k.outTupleSize).toBe(3);
    expect(k.wgsl).toMatch(/let v\d+ = v\d+ \+ vec3<f32>\(v\d+\);/);
  });

  it("vec concatenates mixed-size children", () => {
    const k = compileFieldSpec({ fn: "vec", args: [{ fn: "attribute", name: "uv" }, 1] }, LAYOUT);
    expect(k.outTupleSize).toBe(3);
    expect(k.wgsl).toMatch(/let v\d+ = vec3<f32>\(v\d+, v\d+\);/);
  });

  it("component extracts by swizzle", () => {
    const k = compileFieldSpec({ fn: "component", args: [{ fn: "position" }], index: 2 }, LAYOUT);
    expect(k.outTupleSize).toBe(1);
    expect(k.wgsl).toMatch(/let v\d+ = v\d+\.z;/);
  });

  it("compares emit 1/0 selects and select tests cond != 0", () => {
    const lt = compileFieldSpec({ fn: "lt", args: [{ fn: "attribute", name: "density" }, 1] }, LAYOUT);
    expect(lt.wgsl).toMatch(/select\(0f, 1f, v\d+ < v\d+\)/);
    const sel = compileFieldSpec({ fn: "select", args: [{ fn: "attribute", name: "density" }, 1, 2] }, LAYOUT);
    expect(sel.wgsl).toMatch(/select\(v\d+, v\d+, v\d+ != 0f\)/);
  });

  it("ne codegen is eq's codegen with the operator negated", () => {
    // The CPU pair is exact complements; the device pair has to be the
    // same two lines apart from `==` / `!=`, or the GPU path would answer
    // a different question than the one the node advertises.
    const args: FieldSpecArg[] = [{ fn: "attribute", name: "density" }, 1];
    const eqWgsl = compileFieldSpec({ fn: "eq", args }, LAYOUT).wgsl;
    const neWgsl = compileFieldSpec({ fn: "ne", args }, LAYOUT).wgsl;
    expect(neWgsl).toMatch(/select\(0f, 1f, v\d+ != v\d+\)/);
    expect(neWgsl).toBe(eqWgsl.replace(" == ", " != "));
  });

  it("normalize guards zero tuples like the CPU", () => {
    const k = compileFieldSpec({ fn: "normalize", args: [{ fn: "position" }] }, LAYOUT);
    expect(k.wgsl).toMatch(/select\(0f, 1f \/ sqrt\(v\d+\), v\d+ > 0f\)/);
  });

  it("serializes -0 constants distinctly", () => {
    const k = compileFieldSpec({ fn: "constant", value: [-0, 0] }, LAYOUT);
    expect(k.wgsl).toContain("vec2<f32>(-0f, 0f)");
  });

  it("noise sample transform is always emitted (CPU computes p*f+o at defaults)", () => {
    const k = compileFieldSpec({ fn: "valueNoise" }, LAYOUT);
    expect(k.wgsl).toMatch(/let v\d+ = v\d+ \* 1f \+ vec3<f32>\(0f, 0f, 0f\);/);
  });

  it("identical ramps and fbms share one helper", () => {
    const stops = [
      [0, 0],
      [1, 2],
    ];
    const k = compileFieldSpec(
      {
        fn: "add",
        args: [
          { fn: "ramp", args: [{ fn: "attribute", name: "density" }], stops },
          { fn: "ramp", args: [{ fn: "index" }], stops },
        ],
      },
      LAYOUT,
    );
    expect(count(k.wgsl, "fn pcg_ramp_")).toBe(1);
    expect(count(k.wgsl, "pcg_ramp_0(")).toBe(3); // definition + two calls
  });

  it("compiles a raw number or tuple root by wrapping into constant", () => {
    const n = compileFieldSpec(2.5, LAYOUT);
    expect(n.wgsl).toContain("let v0 = 2.5f;");
    const t = compileFieldSpec([1, 2], LAYOUT);
    expect(t.outTupleSize).toBe(2);
    expect(t.wgsl).toContain("vec2<f32>(1f, 2f)");
  });

  it("position works when P is the only layout attribute", () => {
    const k = compileFieldSpec({ fn: "position" }, { attributes: { P: { type: "f32", tupleSize: 3 } } });
    expect(k.outTupleSize).toBe(3);
    expect(k.outType).toBe("f32");
    expect(k.inputs).toEqual([{ name: "P", type: "f32", tupleSize: 3, binding: 1 }]);
  });
});

/**
 * `param` lowers to a uniform slot rather than a literal, which is what
 * makes ONE compiled kernel serve every value a name is bound to. These
 * pin the three things that has to be true of: the emitted struct and
 * read, the absence of a storage buffer, and a key that carries names
 * and arities but never values.
 */
describe("param uniform slots", () => {
  const bound = (spec: FieldSpec, bindings: Record<string, number | readonly number[]>): FieldSpec =>
    // The bindings ride the spec `fieldFromJson` attaches — the same
    // object `deviceSpec` hands the compiler at cook time.
    peekFieldSpec(fieldFromJson(spec, bindings)) as FieldSpec;

  it("declares the slot array and reads it, with no value in the text", () => {
    const k = compileFieldSpec(bound({ fn: "param", name: "amp" }, { amp: 0.375 }), LAYOUT);
    expect(k.wgsl).toContain("  chunkOffset: u32,\n  _pad0: u32,\n  consts: array<vec4<f32>, 1>,");
    expect(k.wgsl).toContain("let v0 = params.consts[0].x;");
    expect(k.wgsl).not.toContain("0.375");
    expect(k.constSlots).toBe(1);
    expect(k.paramNames).toEqual(["amp"]);
    expect(k.uniformBytes).toBe(32);
  });

  it("costs a uniform slot and NO storage buffer", () => {
    // The saving that justifies the feature: carrying the same value in
    // an attribute column spends one of the seven usable storage slots.
    const k = compileFieldSpec(bound({ fn: "param", name: "amp" }, { amp: 1 }), LAYOUT);
    expect(k.inputs).toEqual([]);
    expect(k.bindings.output).toBe(1);
  });

  it("allocates one slot per distinct name, in sorted-name order", () => {
    const k = compileFieldSpec(
      bound(
        {
          fn: "add",
          args: [
            { fn: "mul", args: [{ fn: "param", name: "b" }, { fn: "param", name: "a" }] },
            { fn: "param", name: "b" },
          ],
        },
        { a: 2, b: 3 },
      ),
      LAYOUT,
    );
    expect(k.paramNames).toEqual(["a", "b"]);
    expect(k.constSlots).toBe(2);
    // Repeated references share their name's slot rather than taking one.
    expect(k.wgsl).toContain("params.consts[0].x"); // a
    expect(k.wgsl).toContain("params.consts[1].x"); // b
    expect(k.uniformBytes).toBe(48);
  });

  it("binds a tuple as the matching vector", () => {
    const k = compileFieldSpec(bound({ fn: "param", name: "off" }, { off: [1, 2, 3] }), LAYOUT);
    expect(k.wgsl).toContain(
      "let v0 = vec3<f32>(params.consts[0].x, params.consts[0].y, params.consts[0].z);",
    );
    expect(k.outTupleSize).toBe(3);
  });

  it("compiles unbound: the name is all a kernel needs", () => {
    const unbound = compileFieldSpec({ fn: "param", name: "amp" }, LAYOUT);
    const withValue = compileFieldSpec(bound({ fn: "param", name: "amp" }, { amp: 4 }), LAYOUT);
    expect(unbound.wgsl).toBe(withValue.wgsl);
    expect(unbound.key).toBe(withValue.key);
  });

  it("keys on names and arities, never on values", () => {
    const spec: FieldSpec = { fn: "param", name: "amp" };
    const a = compileFieldSpec(bound(spec, { amp: 1 }), LAYOUT);
    const b = compileFieldSpec(bound(spec, { amp: 999.5 }), LAYOUT);
    // Same key, same text: rebinding must hit the pipeline cache, or a
    // slider drag would compile a pipeline per tick.
    expect(b.key).toBe(a.key);
    expect(b.wgsl).toBe(a.wgsl);
    expect(a.key).toContain('|params=["amp":1]');

    // Arity is not a value, and it does change the text — so it is in
    // the key, or the two would collide on one cache entry.
    const vec = compileFieldSpec(bound(spec, { amp: [1, 2, 3] }), LAYOUT);
    expect(vec.key).not.toBe(a.key);
    expect(vec.key).toContain('|params=["amp":3]');
  });

  it("leaves a param-free kernel's key and text exactly as they were", () => {
    // The signature is appended only when there are params, so every
    // pre-existing kernel keeps its identity and its cached pipeline.
    const k = compileFieldSpec({ fn: "add", args: [1, 2] }, LAYOUT);
    expect(k.key).not.toContain("params=");
    expect(k.wgsl).not.toContain("consts");
    expect(k.constSlots).toBe(0);
    expect(k.paramNames).toEqual([]);
    expect(k.uniformBytes).toBe(12);
  });

  it("rejects arities one slot cannot hold or reconcile", () => {
    expect(() => compileFieldSpec(bound({ fn: "param", name: "w" }, { w: [1, 2, 3, 4, 5] }), LAYOUT)).toThrow(
      /bound to a 5-tuple, but a uniform slot holds 4 components/,
    );
  });

  it("turns a spec's bindings into the slot payload, zero-padded", () => {
    const spec = bound(
      { fn: "add", args: [{ fn: "param", name: "b" }, { fn: "param", name: "a" }] },
      { a: 0.5, b: [1, 2, 3] },
    );
    const k = compileFieldSpec(spec, LAYOUT);
    const values = paramConstValues(spec, k);
    expect("values" in values && Array.from(values.values)).toEqual([0.5, 0, 0, 0, 1, 2, 3, 0]);
  });

  it("refuses to produce a payload it would have to invent", () => {
    const unbound = compileFieldSpec({ fn: "param", name: "amp" }, LAYOUT);
    // Unbound: the CPU field throws, so the device must decline rather
    // than write a zero the CPU never produced.
    const missing = paramConstValues({ fn: "param", name: "amp" }, unbound);
    expect("problem" in missing && missing.problem).toMatch(/param "amp" has no bound value/);
  });
});

/**
 * A `param` bound to a FIELD lowers the other way, and has to: it is an
 * expression, not a value, so it is compiled IN PLACE. These pin what
 * that costs and what it must not break — no uniform slot, the spliced
 * field's attributes bound like any other, and a kernel key that carries
 * the spliced STRUCTURE (which decides the text) while a spliced number
 * still does not.
 */
describe("param field splices", () => {
  const spliced = (spec: FieldSpec, bindings: Record<string, unknown>): FieldSpec =>
    peekFieldSpec(fieldFromJson(spec, bindings as never)) as FieldSpec;

  const SCALED: FieldSpec = { fn: "mul", args: [{ fn: "position" }, { fn: "param", name: "amp" }] };

  it("compiles the bound expression in place, with no slot and no header", () => {
    const spec = spliced(SCALED, { amp: fieldFromJson({ fn: "fraction" }) });
    const k = compileFieldSpec(spec, LAYOUT);
    expect(k.constSlots).toBe(0);
    expect(k.paramNames).toEqual([]);
    // Character for character what a param-free kernel emits: the const
    // tail is appended only when a slot is claimed.
    expect(k.uniformBytes).toBe(12);
    expect(k.wgsl).not.toContain("consts");
    expect(k.wgsl).toContain("let v1 = f32(i) / f32(max(params.count, 2u) - 1u);");
    // ...and identical to the same expression written out by hand.
    expect(k.wgsl).toBe(
      compileFieldSpec({ fn: "mul", args: [{ fn: "position" }, { fn: "fraction" }] }, LAYOUT).wgsl,
    );
  });

  it("binds the attributes the spliced field reads, which the pre-pass must find", () => {
    // The failure this prevents is a kernel body referencing an input the
    // pre-pass never bound — the one thing the pre-pass exists for.
    const spec = spliced(SCALED, { amp: fieldFromJson({ fn: "attribute", name: "density" }) });
    const k = compileFieldSpec(spec, LAYOUT);
    expect(k.inputs.map((i) => i.name).sort()).toEqual(["P", "density"]);
    expect(k.wgsl).toContain("in1[i]");
  });

  it("puts the spliced structure in the kernel key, where a value never goes", () => {
    const a = compileFieldSpec(spliced(SCALED, { amp: fieldFromJson({ fn: "fraction" }) }), LAYOUT);
    const b = compileFieldSpec(spliced(SCALED, { amp: fieldFromJson({ fn: "index" }) }), LAYOUT);
    // Two expressions, two kernels — they are different WGSL, so sharing
    // a key would serve one field's text for the other's bytes.
    expect(a.key).not.toBe(b.key);
    // The same expression twice is one kernel, whatever object carried it.
    expect(compileFieldSpec(spliced(SCALED, { amp: fieldFromJson({ fn: "fraction" }) }), LAYOUT).key).toBe(
      a.key,
    );
    // And a VALUE binding beside a spliced one still keeps its value out
    // of the key: only the name and arity of the uniform show up.
    const mixed: FieldSpec = {
      fn: "add",
      args: [{ fn: "param", name: "amp" }, { fn: "param", name: "bias" }],
    };
    const one = compileFieldSpec(spliced(mixed, { amp: fieldFromJson({ fn: "fraction" }), bias: 1 }), LAYOUT);
    const two = compileFieldSpec(spliced(mixed, { amp: fieldFromJson({ fn: "fraction" }), bias: 9 }), LAYOUT);
    expect(one.key).toBe(two.key);
    expect(one.paramNames).toEqual(["bias"]);
    expect(one.constSlots).toBe(1);
  });

  it("writes the payload for the value bindings only", () => {
    const mixed: FieldSpec = {
      fn: "add",
      args: [{ fn: "param", name: "amp" }, { fn: "param", name: "bias" }],
    };
    const spec = spliced(mixed, { amp: fieldFromJson({ fn: "fraction" }), bias: 0.25 });
    const k = compileFieldSpec(spec, LAYOUT);
    const values = paramConstValues(spec, k);
    expect("values" in values && Array.from(values.values)).toEqual([0.25, 0, 0, 0]);
  });

  it("refuses a binding that carries no spec, where it is still known", () => {
    // `deviceSpec` declines an expression whose ROOT records an opaque
    // binding, so a root case never reaches the compiler. This is the
    // other door: a spec COMPOSED over such an expression carries no
    // record of its own, and lowering the reference as an unbound uniform
    // would dispatch a zero the CPU never produced.
    const opaque = makeField("compile_opaque", 1, (ctx) => ({
      data: new Float32Array(ctx.geo.attrs[ctx.domain].count),
      tupleSize: 1,
    }));
    const inner = fieldFromJson(SCALED, { amp: opaque });
    const composed: FieldSpec = { fn: "add", args: [peekFieldSpec(inner) as FieldSpec, 1] };
    expect(() => compileFieldSpec(composed, LAYOUT)).toThrow(
      /param "amp" is bound to a Field that carries no spec/,
    );
  });

  it("lowers one name two ways when two scopes bound it two ways", () => {
    // Reachable by composing separately built fields, and INVITED by the
    // shipped vocabulary, which reuses `amount`/`frequency`/`variant`
    // across primitives: a knob bound to a field that was itself built
    // with a binding of the same name. The two references are different
    // values in different scopes, and nothing has to be reconciled — the
    // lowering is decided per NODE, so the spliced one compiles in place
    // while the value-bound one gets the slot.
    const inner = fieldFromJson({ fn: "param", name: "amp" }, { amp: fieldFromJson({ fn: "fraction" }) });
    const outer = fieldFromJson({ fn: "add", args: [{ fn: "param", name: "amp" }, 1] }, { amp: 2 });
    const merged: FieldSpec = {
      fn: "add",
      args: [peekFieldSpec(inner) as FieldSpec, peekFieldSpec(outer) as FieldSpec],
    };
    const k = compileFieldSpec(merged, LAYOUT);
    // One slot, for the one reference that needs one.
    expect(k.paramNames).toEqual(["amp"]);
    expect(k.constSlots).toBe(1);
    expect(k.wgsl).toContain("let v0 = f32(i) / f32(max(params.count, 2u) - 1u);");
    expect(k.wgsl).toContain("params.consts[0].x");
    const values = paramConstValues(merged, k);
    expect("values" in values && Array.from(values.values)).toEqual([2, 0, 0, 0]);
  });
});

describe("param plan failures are decided once", () => {
  it("remembers a contradiction instead of re-deriving it every cook", () => {
    // The evaluator caches compile FAILURES in its kernel map; a plan
    // failure happens before a cache key exists, so it is remembered here
    // or not at all. Identity, not just equality: the same Error object.
    const spec = peekFieldSpec(
      fieldFromJson({ fn: "param", name: "w" }, { w: [1, 2, 3, 4, 5] }),
    ) as FieldSpec;
    const first = (() => {
      try {
        compileFieldSpec(spec, LAYOUT);
      } catch (err) {
        return err;
      }
      throw new Error("expected a compile failure");
    })();
    expect(() => compileFieldSpec(spec, LAYOUT)).toThrow(/bound to a 5-tuple/);
    try {
      compileFieldSpec(spec, LAYOUT);
    } catch (second) {
      expect(second).toBe(first);
    }
  });
});
