/**
 * WGSL compiler for the serializable field-expression grammar
 * (`fieldJson`). Codegen only: `compileFieldSpec` lowers a FieldSpec to
 * a complete WGSL compute kernel plus a bind-layout plan — nothing here
 * touches a GPU device (that is the phase-20 runtime).
 *
 * Semantics are ported from the CPU field implementations
 * (`src/fields`, `src/noise`), which remain the bit-exact reference:
 *
 * - Integer and hash paths (`randomField`, noise lattice hashing) are
 *   bit-exact u32 ports.
 * - Float arithmetic computes in f32 where the CPU computes in f64 and
 *   stores f32. For + − × this yields identical f32 results by IEEE
 *   double-rounding innocuousness; division, sqrt, and transcendental
 *   builtins may differ within tolerances phase 20 measures.
 * - Branchy ops (select, compares, ramp stops, worley cell walks) can
 *   flip at knife-edge inputs whose operands differ within tolerance.
 *
 * Tuple sizes 1–4 map to f32 / vecN<f32>. The CPU grammar can build
 * wider tuples (via `vec` concatenation, wide constants, or wide
 * attributes); those are rejected with an actionable error — evaluate
 * such fields on the CPU. `index` is exact up to 2^24 on GPU when used
 * inside float arithmetic (f32 mantissa); as the kernel root it is
 * written as raw u32 and exact everywhere.
 */
import { opaqueParam, paramSpecOf, paramValue } from "../fields/spec.js";
import type { FieldSpec, FieldSpecArg } from "../fields/fieldJson.js";
import { fieldFromJson, fieldFromJsonValueFree } from "../fields/fieldJson.js";
import { hashCombine, hashString } from "../random/hash.js";
import { APPLY_CONST_COMPONENTS, applyUniformBytes } from "./applyKernels.js";
import { NOISE_RAW_RANGES, type NoiseRange, hash2 } from "../noise/util.js";
import { VALUE_SALT } from "../noise/value.js";
import { PERLIN_SALT } from "../noise/perlin.js";
import { SIMPLEX_SALT } from "../noise/simplex.js";
import { WORLEY_SALT } from "../noise/worley.js";
import {
  type AttrIsSlot,
  type CompiledFieldKernel,
  type FieldKernelAttr,
  type FieldKernelLayout,
  GpuCompileError,
  type GpuScalarType,
  type KernelInput,
} from "./types.js";
import { libClosure, wgslF32, wgslHexU32, wgslU32 } from "./wgslLib.js";

/** 1D workgroup size every generated kernel dispatches with. */
const WORKGROUP_SIZE = 64;

/**
 * Codegen version prefix folded into specialization keys. Bumped
 * whenever the emitted WGSL text changes (wgsl2: chunk-offset uniform
 * member for chunked 1D dispatch) so pipeline caches keyed by kernel key
 * can never serve modules generated by an older codegen.
 */
const CODEGEN_VERSION = "wgsl2";

const XYZW = ["x", "y", "z", "w"] as const;

// ---------------------------------------------------------------------------
// small predicates (kept local; fieldJson has validated shapes already)

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function tupleError(path: string, what: string, size: number): GpuCompileError {
  return new GpuCompileError(
    `${path}: ${what} has tupleSize ${size}, but GPU kernels support tuple sizes 1 to 4; ` +
      "evaluate this field on the CPU instead, or split it into components",
  );
}

/**
 * Static broadcast rule, mirroring the CPU `broadcastTupleSize`: scalars
 * broadcast against any size; non-scalar sizes must match exactly. All
 * sizes are statically known on the GPU path (attributes come from the
 * layout), so this always resolves or throws.
 */
function broadcastSizes(kind: string, path: string, sizes: readonly number[]): number {
  let ts = 1;
  for (const s of sizes) {
    if (s === 1) continue;
    if (ts !== 1 && ts !== s) {
      throw new GpuCompileError(`${path}: ${kind}: incompatible tuple sizes ${ts} and ${s}`);
    }
    ts = s;
  }
  return ts;
}

// ---------------------------------------------------------------------------
// compile context

/** An SSA value in the kernel body: a `let` name and its tuple size. */
interface Val {
  readonly ref: string;
  readonly size: number;
}

interface BoundAttr {
  readonly name: string;
  readonly varName: string;
  readonly binding: number;
  readonly attr: FieldKernelAttr;
}

class CompileCtx {
  readonly layout: FieldKernelLayout;
  readonly params: ParamPlan;
  readonly lines: string[] = [];
  readonly libRoots = new Set<string>();
  usesSeed = false;

  private readonly valueNumbers = new Map<string, Val>();
  private readonly bindings = new Map<string, BoundAttr>();
  private readonly helpers = new Map<string, string>(); // content key -> fn name
  private readonly helperTexts: string[] = [];
  private readonly helperCounters = new Map<string, number>();
  private varCounter = 0;

  constructor(layout: FieldKernelLayout, boundNames: readonly string[], params: ParamPlan) {
    this.layout = layout;
    this.params = params;
    boundNames.forEach((name, i) => {
      this.bindings.set(name, {
        name,
        varName: `in${i}`,
        binding: i + 1,
        attr: layout.attributes[name],
      });
    });
  }

  /** The pre-assigned uniform slot for a param known to be in the plan. */
  paramSlot(name: string): { slot: number; arity: number } {
    const slot = this.params.slots.get(name);
    if (slot === undefined) throw new Error(`internal: param ${JSON.stringify(name)} was not pre-planned`);
    return { slot, arity: this.params.arities[slot] };
  }

  /** The pre-assigned uniform slot for an `attributeIs` (attribute, literal) pair. */
  attrIsSlot(name: string, value: string): number {
    const slot = this.params.attrIsSlots.get(attrIsKey(name, value));
    if (slot === undefined) {
      throw new Error(`internal: attributeIs ${attrIsKey(name, value)} was not pre-planned`);
    }
    return slot;
  }

  /** Emit (or reuse) an SSA `let` for a canonical expression. */
  emit(expr: string, size: number): Val {
    const hit = this.valueNumbers.get(expr);
    if (hit) return hit;
    const val: Val = { ref: `v${this.varCounter++}`, size };
    this.lines.push(`  let ${val.ref} = ${expr};`);
    this.valueNumbers.set(expr, val);
    return val;
  }

  /** The pre-assigned binding for an attribute known to be eligible. */
  binding(name: string): BoundAttr {
    const b = this.bindings.get(name);
    if (!b) throw new Error(`internal: attribute ${JSON.stringify(name)} was not pre-bound`);
    return b;
  }

  boundAttrs(): BoundAttr[] {
    return [...this.bindings.values()];
  }

  /**
   * Register a helper function (ramp / fbm instance) deduplicated by
   * body content. `body` uses the placeholder `@NAME@` for its own name.
   */
  helper(kind: string, body: string): string {
    const existing = this.helpers.get(body);
    if (existing) return existing;
    const n = this.helperCounters.get(kind) ?? 0;
    this.helperCounters.set(kind, n + 1);
    const name = `pcg_${kind}_${n}`;
    this.helpers.set(body, name);
    this.helperTexts.push(body.replaceAll("@NAME@", name));
    return name;
  }

  helperBlocks(): readonly string[] {
    return this.helperTexts;
  }
}

/** Reference `v` at tuple size `size`, splatting scalars into vectors. */
function splat(v: Val, size: number): string {
  return v.size === size ? v.ref : `vec${size}<f32>(${v.ref})`;
}

function zeroLit(size: number): string {
  return size === 1 ? "0f" : `vec${size}<f32>(0f)`;
}

function oneLit(size: number): string {
  return size === 1 ? "1f" : `vec${size}<f32>(1f)`;
}

// ---------------------------------------------------------------------------
// attribute access

function describeLayout(layout: FieldKernelLayout): string {
  const names = Object.keys(layout.attributes).sort();
  if (names.length === 0) return "the layout declares no attributes";
  return `layout attributes: ${names.map((n) => JSON.stringify(n)).join(", ")}`;
}

/**
 * Validate an attribute reference against the layout. `origin` prefixes
 * the message for indirect reads (`position` reads `P`).
 */
function resolveLayoutAttr(
  ctx: CompileCtx,
  path: string,
  name: string,
  expectTupleSize: number | undefined,
  origin: string,
): FieldKernelAttr {
  const attrs = ctx.layout.attributes;
  if (!Object.hasOwn(attrs, name)) {
    throw new GpuCompileError(
      `${path}: ${origin}attribute ${JSON.stringify(name)} is not in the kernel layout; ${describeLayout(ctx.layout)}`,
    );
  }
  const attr = attrs[name];
  if (attr.type === "string") {
    throw new GpuCompileError(
      `${path}: ${origin}attribute ${JSON.stringify(name)} has type "string"; a string column has ` +
        "no numeric value to read — test it with " +
        `{ fn: "attributeIs", name: ${JSON.stringify(name)}, value: "..." }, which is 1 where it ` +
        "matches and 0 elsewhere, or read a numeric or bool attribute",
    );
  }
  if (expectTupleSize !== undefined && attr.tupleSize !== expectTupleSize) {
    throw new GpuCompileError(
      `${path}: ${origin}attribute ${JSON.stringify(name)}: expected tupleSize ${expectTupleSize}, ` +
        `got ${attr.tupleSize} in the kernel layout`,
    );
  }
  if (attr.tupleSize > 4) {
    throw tupleError(path, `${origin}attribute ${JSON.stringify(name)}`, attr.tupleSize);
  }
  return attr;
}

/**
 * Load an attribute as an f32 expression value (i32/u32/bool lanes are
 * converted with `f32(...)`, mirroring the CPU number/bool→f32 read).
 */
function loadAttribute(
  ctx: CompileCtx,
  path: string,
  name: string,
  expectTupleSize: number | undefined,
  origin: string,
): Val {
  const attr = resolveLayoutAttr(ctx, path, name, expectTupleSize, origin);
  const b = ctx.binding(name);
  const ts = attr.tupleSize;
  const conv = (e: string): string => (attr.type === "f32" ? e : `f32(${e})`);
  if (ts === 1) return ctx.emit(conv(`${b.varName}[i]`), 1);
  const lanes: string[] = [];
  for (let k = 0; k < ts; k++) {
    lanes.push(conv(`${b.varName}[${flatIndex(ts, k)}]`));
  }
  return ctx.emit(`vec${ts}<f32>(${lanes.join(", ")})`, ts);
}

function flatIndex(ts: number, k: number): string {
  if (ts === 1) return "i";
  return k === 0 ? `i * ${ts}u` : `i * ${ts}u + ${k}u`;
}

// ---------------------------------------------------------------------------
// handlers

type Handler = (spec: Record<string, unknown>, path: string, ctx: CompileCtx) => Val;

const HANDLERS = new Map<string, Handler>();

/** Field fns the WGSL compiler supports, sorted (derived from its handler table). */
export function supportedGpuFieldFns(): string[] {
  return [...HANDLERS.keys()].sort();
}

function compileNode(spec: Record<string, unknown>, path: string, ctx: CompileCtx): Val {
  const fn = String(spec.fn);
  const handler = HANDLERS.get(fn);
  if (!handler) {
    throw new GpuCompileError(
      `${path}: field fn "${fn}" is not supported by the WGSL compiler; ` +
        `supported fns: ${supportedGpuFieldFns().join(", ")}`,
    );
  }
  return handler(spec, path, ctx);
}

function compileArg(v: unknown, path: string, ctx: CompileCtx): Val {
  if (typeof v === "number") return ctx.emit(wgslF32(v, path), 1);
  if (Array.isArray(v)) return compileConstantTuple(v as number[], path, ctx);
  return compileNode(v as Record<string, unknown>, path, ctx);
}

function compileConstantTuple(values: readonly number[], path: string, ctx: CompileCtx): Val {
  const ts = values.length;
  if (ts > 4) throw tupleError(path, "constant", ts);
  if (ts === 1) return ctx.emit(wgslF32(values[0], path), 1);
  const lits = values.map((v) => wgslF32(v, path));
  return ctx.emit(`vec${ts}<f32>(${lits.join(", ")})`, ts);
}

function specArgs(spec: Record<string, unknown>): unknown[] {
  return spec.args as unknown[];
}

// -- inputs -----------------------------------------------------------------

HANDLERS.set("constant", (spec, path, ctx) => {
  const v = spec.value;
  if (typeof v === "number") return ctx.emit(wgslF32(v, `${path}.value`), 1);
  return compileConstantTuple(v as number[], `${path}.value`, ctx);
});

HANDLERS.set("attribute", (spec, path, ctx) => {
  const name = spec.name as string;
  const expect = spec.tupleSize as number | undefined;
  return loadAttribute(ctx, path, name, expect, "");
});

/**
 * Validate the STRING column `attributeIs` tests. Deliberately not
 * `resolveLayoutAttr`, which refuses strings wholesale and is right to:
 * a string column has no numeric value, so `attribute("species")` has
 * nothing to read. This one reads no value either — it compares an index
 * against an index — so the refusal it needs is the mirror image, and a
 * NUMERIC column is the mistake here. The message names `eq` for the
 * same reason the CPU constructor does: absence of a value is data,
 * absence of the right KIND of attribute is a bug the author can fix.
 *
 * No tuple cap, unlike the numeric path: only component 0 is read, so a
 * wide string tuple costs nothing and never has to fit in a `vecN`.
 */
function resolveStringAttr(ctx: CompileCtx, path: string, name: string): FieldKernelAttr {
  const attrs = ctx.layout.attributes;
  if (!Object.hasOwn(attrs, name)) {
    throw new GpuCompileError(
      `${path}: attributeIs: attribute ${JSON.stringify(name)} is not in the kernel layout; ${describeLayout(ctx.layout)}`,
    );
  }
  const attr = attrs[name];
  if (attr.type !== "string") {
    throw new GpuCompileError(
      `${path}: attributeIs: attribute ${JSON.stringify(name)} has type ${JSON.stringify(attr.type)}, ` +
        "but attributeIs tests a string attribute; compare a numeric attribute with " +
        `{ fn: "eq", args: [{ fn: "attribute", name: ${JSON.stringify(name)} }, <number>] }`,
    );
  }
  return attr;
}

// The literal rides a UNIFORM SLOT and is never baked, and unlike `param`
// — where the uniform is the better of two workable lowerings — here it
// is the only sound one. What the kernel needs is the literal's index in
// THIS geometry's string table, and that index is a property of the
// geometry rather than of the spec: the table is insertion-ordered and
// rebuilt by clone, filter and merge, so two cells of one world hold
// "pine" at different indices. The kernel cache key is spec text plus
// each attribute's name/type/tupleSize (`evaluator.ts`) and carries no
// table contents, so a baked index would be shared by two geometries
// that disagree about it — the cache would serve the wrong constant, and
// silently, which is the failure this whole design exists to prevent.
// Riding a uniform makes the kernel table-agnostic: one kernel, one
// index resolved per dispatch against the geometry in hand.
//
// Component 0 of a possibly-tuple column, matching `Attribute.getString`'s
// default and so the CPU `attributeIs`; the stride is applied for the
// same reason every other read applies it.
//
// -1 for an absent literal (filled by `constSlotValues`) needs no special
// case here: no table index equals it, so the comparison is false on
// every lane and the column is the zeros the CPU produces — `f32(u32)`
// is non-negative for every bit pattern, garbage included.
//
// The comparison is f32 where the CPU's is integer, which is exact up to
// 2^24 — the same bound the module doc records for `index`, and reached
// here only by a string table holding more than 16.7 million DISTINCT
// values on one attribute. Past it two indices could round together and
// the device would match an element the CPU does not. Recorded rather
// than guarded because the uniform tail is f32 for every slot kind and
// the case is unreachable in any geometry the library can build.
HANDLERS.set("attributeIs", (spec, path, ctx) => {
  const name = spec.name as string;
  const value = spec.value as string;
  const attr = resolveStringAttr(ctx, path, name);
  const b = ctx.binding(name);
  const slot = ctx.attrIsSlot(name, value);
  return ctx.emit(
    `select(0f, 1f, f32(${b.varName}[${flatIndex(attr.tupleSize, 0)}]) == params.consts[${slot}].x)`,
    1,
  );
});

HANDLERS.set("position", (_spec, path, ctx) => {
  return loadAttribute(ctx, path, "P", 3, "position reads ");
});

// A named value lowers to a UNIFORM SLOT, never to a literal — forced
// rather than chosen. `compileFieldSpec` is handed a spec and never
// values, so a literal lowering has nowhere to read from; and the uniform
// is the path this runtime already settled on next door, where a constant
// apply param "contributes its tuple size and slot — never its values, so
// a constant edit rebinds the uniform and reuses the pipeline"
// (applyKernels.ts). Two further properties fall out of that: it costs no
// storage buffer (`collectAttrNames` finds nothing in a `param`, which is
// the whole saving against carrying the value in an attribute column),
// and it is BIT-EXACT against the CPU — better than a literal, since a
// WGSL front end may flush a `-0` or subnormal literal to `+0` but never
// a uniform load (see run.ts).
//
// The arity comes from the binding recorded on this spec node, not from
// the value: it decides the emitted text, so it is in the specialization
// key, while the value is not. An unbound param compiles as a scalar —
// nothing will ever dispatch it (the evaluator declines, so the CPU
// raises the actionable refusal), but it must still COMPILE, because the
// key and the kernel are exactly what a compiler needs from an unbound
// reference.
//
// A FIELD binding lowers the other way, and has to: it is not one value
// but an expression, so it is COMPILED IN PLACE, exactly as if the author
// had written it here. That costs no uniform slot and no storage buffer
// of its own — whatever attributes it reads are already in the pre-pass,
// which walks into it (`collectAttrNames`) — and it fuses into the same
// kernel rather than adding a dispatch, which is the improvement over the
// per-point attribute column this route replaces. The value-free kernel
// key rebuilds it for the same reason (`specKernelKey`): a spliced field
// decides the emitted text, so it belongs to the kernel's identity, where
// a spliced number deliberately does not.
HANDLERS.set("param", (spec, path, ctx) => {
  const name = spec.name as string;
  const bound = paramSpecOf(spec as unknown as FieldSpec);
  if (bound !== undefined) {
    return compileNode(bound as unknown as Record<string, unknown>, `${path}<${name}>`, ctx);
  }
  const { slot, arity } = ctx.paramSlot(name);
  const read = (k: number): string => `params.consts[${slot}].${XYZW[k]}`;
  if (arity === 1) return ctx.emit(read(0), 1);
  return ctx.emit(`vec${arity}<f32>(${Array.from({ length: arity }, (_v, k) => read(k)).join(", ")})`, arity);
});

HANDLERS.set("index", (_spec, _path, ctx) => ctx.emit("f32(i)", 1));

// Normalized index: i / (count - 1), the closed [0, 1] span. `max(count,
// 2u) - 1u` is the CPU's `n > 1 ? n - 1 : 1` written without a branch —
// at count 1 the lone lane divides by 1 and reads 0, exactly as the CPU
// does, and the divisor can never be 0. (Count 0 dispatches nothing on
// either side.)
HANDLERS.set("fraction", (_spec, _path, ctx) =>
  ctx.emit("f32(i) / f32(max(params.count, 2u) - 1u)", 1),
);

// The node seed is already a uniform (`params.seed`, written per
// dispatch), so this leaf costs no binding, no const slot, and — the
// part that matters — nothing in `kernel.key`, which is a function of
// the SPEC. One kernel serves every seed the graph is ever given, where
// a baked literal would have specialized a pipeline per seed into an
// unbounded cache: the two-keys hazard `param` documented, arriving here
// as a value that changes on every drag of the seed box.
//
// Split rather than `f32(params.seed)`. The CPU column is an f32, so
// the value both sides must agree on is the nearest f32 to a full u32,
// and a u32 past 2^24 is exactly the case where converting it whole is
// LOSSY — which for a hashed node seed is not an edge case but every
// value. Rather than depend on how a given adapter rounds that
// conversion, the pieces are made exact and the rounding is left to one
// correctly-rounded add: `seed >> 8` is under 2^24 and converts
// exactly, `* 256.0` only moves the exponent, and the sum is
// `Math.fround(seed)`. Measured both ways on the reference adapter
// (RTX 5090, D3D12) — it agrees either way, which is the point: this
// spelling does not need it to.
HANDLERS.set("nodeSeed", (_spec, _path, ctx) => {
  ctx.usesSeed = true;
  return ctx.emit("f32(params.seed >> 8u) * 256.0 + f32(params.seed & 0xFFu)", 1);
});

// randomField is keyed on POINT IDENTITY on the CPU (see
// `src/data/identity.ts`): the f32 bit patterns of P.xyz hashed with the
// `seed` attribute, then folded into (params.seed, key). A layout carries
// no domain, so a spec compiled against one without P — vertex, primitive
// or detail, where the CPU falls back to the element index — throws here
// and resolves on the CPU instead of inventing a key the CPU never used.
HANDLERS.set("randomField", (spec, path, ctx) => {
  const key = spec.key;
  const keyHash = typeof key === "string" ? hashString(key) : ((key as number | undefined) ?? 0) >>> 0;
  ctx.usesSeed = true;
  ctx.libRoots.add("pcg_hash3");
  ctx.libRoots.add("pcg_hash4");
  ctx.libRoots.add("pcg_hash_float");
  const origin = "randomField's per-point identity reads ";
  const P = resolveLayoutAttr(ctx, path, "P", undefined, origin);
  if (P.tupleSize < 3) {
    throw new GpuCompileError(
      `${path}: ${origin}attribute "P" with x, y and z (tupleSize 3), got tupleSize ${P.tupleSize}`,
    );
  }
  const pVar = ctx.binding("P").varName;
  // Bits, never the value: hashCombine truncates a float toward zero, so
  // every position inside the unit cube would key identically.
  const bits = (k: number): string => {
    const e = `${pVar}[${flatIndex(P.tupleSize, k)}]`;
    return P.type === "f32" ? `bitcast<u32>(${e})` : `bitcast<u32>(f32(${e}))`;
  };
  // A missing `seed` column contributes 0, exactly as a column of
  // defaults would — the CPU makes the same substitution.
  let seedExpr = "0u";
  const seedAttr = Object.hasOwn(ctx.layout.attributes, "seed")
    ? ctx.layout.attributes.seed
    : undefined;
  if (seedAttr !== undefined) {
    if (seedAttr.tupleSize !== 1 || (seedAttr.type !== "u32" && seedAttr.type !== "i32")) {
      throw new GpuCompileError(
        `${path}: ${origin}the standard point attribute "seed" as a u32 or i32 scalar, but the ` +
          `layout has it as ${seedAttr.type}x${seedAttr.tupleSize}; this field resolves on the CPU instead`,
      );
    }
    const sVar = ctx.binding("seed").varName;
    seedExpr = seedAttr.type === "u32" ? `${sVar}[i]` : `bitcast<u32>(${sVar}[i])`;
  }
  const ident = `pcg_hash4(${bits(0)}, ${bits(1)}, ${bits(2)}, ${seedExpr})`;
  return ctx.emit(`pcg_hash_float(pcg_hash3(params.seed, ${wgslHexU32(keyHash)}, ${ident}))`, 1);
});

// -- elementwise combinators ------------------------------------------------

/**
 * Register an elementwise combinator: children broadcast per the scalar
 * rule and the template receives size-matched operand references.
 */
function registerElementwise(name: string, arity: number, template: (refs: string[], size: number) => string): void {
  HANDLERS.set(name, (spec, path, ctx) => {
    const args = specArgs(spec);
    const vals: Val[] = [];
    for (let i = 0; i < arity; i++) {
      vals.push(compileArg(args[i], `${path}.args[${i}]`, ctx));
    }
    const size = broadcastSizes(name, path, vals.map((v) => v.size));
    const refs = vals.map((v) => splat(v, size));
    return ctx.emit(template(refs, size), size);
  });
}

registerElementwise("add", 2, (a) => `${a[0]} + ${a[1]}`);
registerElementwise("sub", 2, (a) => `${a[0]} - ${a[1]}`);
registerElementwise("mul", 2, (a) => `${a[0]} * ${a[1]}`);
registerElementwise("div", 2, (a) => `${a[0]} / ${a[1]}`);
registerElementwise("min", 2, (a) => `min(${a[0]}, ${a[1]})`);
registerElementwise("max", 2, (a) => `max(${a[0]}, ${a[1]})`);
registerElementwise("abs", 1, (a) => `abs(${a[0]})`);
registerElementwise("floor", 1, (a) => `floor(${a[0]})`);
registerElementwise("sin", 1, (a) => `sin(${a[0]})`);
registerElementwise("cos", 1, (a) => `cos(${a[0]})`);
registerElementwise("tan", 1, (a) => `tan(${a[0]})`);
registerElementwise("asin", 1, (a) => `asin(${a[0]})`);
registerElementwise("acos", 1, (a) => `acos(${a[0]})`);
registerElementwise("atan", 1, (a) => `atan(${a[0]})`);
registerElementwise("atan2", 2, (a) => `atan2(${a[0]}, ${a[1]})`);
registerElementwise("clamp", 3, (a) => `clamp(${a[0]}, ${a[1]}, ${a[2]})`);
// CPU lerp is a + (b - a) * t; WGSL mix() is specified as a*(1-t)+b*t,
// which rounds differently — emit the CPU formula.
registerElementwise("lerp", 3, (a) => `${a[0]} + (${a[1]} - ${a[0]}) * ${a[2]}`);
// CPU select takes a where cond != 0; WGSL select(f, t, cond).
registerElementwise("select", 3, (a, size) => `select(${a[2]}, ${a[1]}, ${a[0]} != ${zeroLit(size)})`);
registerElementwise("lt", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} < ${a[1]})`);
registerElementwise("le", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} <= ${a[1]})`);
registerElementwise("gt", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} > ${a[1]})`);
registerElementwise("ge", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} >= ${a[1]})`);
registerElementwise("eq", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} == ${a[1]})`);
registerElementwise("ne", 2, (a, size) => `select(${zeroLit(size)}, ${oneLit(size)}, ${a[0]} != ${a[1]})`);

// remap needs intermediate values (degenerate input span maps to outMin,
// mirroring the CPU; the divisor is guarded so no Inf/NaN is produced in
// the discarded lane).
HANDLERS.set("remap", (spec, path, ctx) => {
  const args = specArgs(spec);
  const vals = args.map((a, i) => compileArg(a, `${path}.args[${i}]`, ctx));
  const size = broadcastSizes("remap", path, vals.map((v) => v.size));
  const [x, inMin, inMax, outMin, outMax] = vals.map((v) => splat(v, size));
  const span = ctx.emit(`${inMax} - ${inMin}`, size);
  const zero = zeroLit(size);
  const safe = ctx.emit(`select(${span.ref}, ${oneLit(size)}, ${span.ref} == ${zero})`, size);
  return ctx.emit(
    `select(${outMin} + ((${x} - ${inMin}) / ${safe.ref}) * (${outMax} - ${outMin}), ${outMin}, ${span.ref} == ${zero})`,
    size,
  );
});

// -- vector / structural ----------------------------------------------------

HANDLERS.set("dot", (spec, path, ctx) => {
  const args = specArgs(spec);
  const a = compileArg(args[0], `${path}.args[0]`, ctx);
  const b = compileArg(args[1], `${path}.args[1]`, ctx);
  const size = broadcastSizes("dot", path, [a.size, b.size]);
  if (size === 1) return ctx.emit(`${a.ref} * ${b.ref}`, 1);
  return ctx.emit(`dot(${splat(a, size)}, ${splat(b, size)})`, 1);
});

HANDLERS.set("length", (spec, path, ctx) => {
  const a = compileArg(specArgs(spec)[0], `${path}.args[0]`, ctx);
  // Scalar: the CPU's sqrt(a*a) in f64 is exactly |a|.
  if (a.size === 1) return ctx.emit(`abs(${a.ref})`, 1);
  const s = ctx.emit(`dot(${a.ref}, ${a.ref})`, 1);
  return ctx.emit(`sqrt(${s.ref})`, 1);
});

HANDLERS.set("normalize", (spec, path, ctx) => {
  const a = compileArg(specArgs(spec)[0], `${path}.args[0]`, ctx);
  const s = a.size === 1 ? ctx.emit(`${a.ref} * ${a.ref}`, 1) : ctx.emit(`dot(${a.ref}, ${a.ref})`, 1);
  // CPU: inv = sum > 0 ? 1 / sqrt(sum) : 0 — zero tuples stay zero.
  const inv = ctx.emit(`select(0f, 1f / sqrt(${s.ref}), ${s.ref} > 0f)`, 1);
  return ctx.emit(`${a.ref} * ${inv.ref}`, a.size);
});

HANDLERS.set("vec", (spec, path, ctx) => {
  const args = specArgs(spec);
  const vals = args.map((a, i) => compileArg(a, `${path}.args[${i}]`, ctx));
  const total = vals.reduce((acc, v) => acc + v.size, 0);
  if (total > 4) throw tupleError(path, "vec result", total);
  if (vals.length === 1) return vals[0];
  return ctx.emit(`vec${total}<f32>(${vals.map((v) => v.ref).join(", ")})`, total);
});

HANDLERS.set("component", (spec, path, ctx) => {
  const a = compileArg(specArgs(spec)[0], `${path}.args[0]`, ctx);
  const idx = spec.index as number;
  if (idx >= a.size) {
    throw new GpuCompileError(`${path}: component: index ${idx} out of range for tupleSize ${a.size}`);
  }
  if (a.size === 1) return a;
  return ctx.emit(`${a.ref}.${XYZW[idx]}`, 1);
});

HANDLERS.set("ramp", (spec, path, ctx) => {
  const a = compileArg(specArgs(spec)[0], `${path}.args[0]`, ctx);
  if (a.size !== 1) {
    throw new GpuCompileError(`${path}: ramp: input must be scalar, got tupleSize ${a.size}`);
  }
  const stops = spec.stops as Array<[number, number]>;
  const name = ctx.helper("ramp", rampHelperBody(stops, `${path}.stops`));
  return ctx.emit(`${name}(${a.ref})`, 1);
});

/**
 * Per-instance piecewise-linear ramp helper, mirroring the CPU: clamp
 * outside the stop range, otherwise interpolate the segment whose upper
 * stop is the first with position >= t. Stop positions/values and the
 * per-segment spans are precomputed in f64 (as on CPU) and serialized
 * as f32. NaN inputs fall through every comparison and return NaN, as
 * on the CPU.
 */
function rampHelperBody(stops: ReadonlyArray<readonly [number, number]>, context: string): string {
  const L = (v: number): string => wgslF32(v, context);
  const last = stops.length - 1;
  const lines: string[] = [];
  lines.push("fn @NAME@(t: f32) -> f32 {");
  lines.push(`  if (t <= ${L(stops[0][0])}) {`);
  lines.push(`    return ${L(stops[0][1])};`);
  lines.push("  }");
  lines.push(`  if (t >= ${L(stops[last][0])}) {`);
  lines.push(`    return ${L(stops[last][1])};`);
  lines.push("  }");
  const interp = (j: number): string => {
    const tPrev = stops[j - 1][0];
    const vPrev = stops[j - 1][1];
    const tSpan = stops[j][0] - tPrev;
    const vDiff = stops[j][1] - vPrev;
    return `${L(vPrev)} + ${L(vDiff)} * ((t - ${L(tPrev)}) / ${L(tSpan)})`;
  };
  for (let j = 1; j < last; j++) {
    lines.push(`  if (t <= ${L(stops[j][0])}) {`);
    lines.push(`    return ${interp(j)};`);
    lines.push("  }");
  }
  if (last >= 1) {
    lines.push(`  return ${interp(last)};`);
  } else {
    // Single stop: only NaN reaches this point; propagate it (CPU does).
    lines.push("  return t;");
  }
  lines.push("}");
  return lines.join("\n");
}

// -- noise ------------------------------------------------------------------

interface NoiseOptsSpec {
  readonly seed?: number;
  readonly frequency?: number;
  readonly offset?: readonly number[];
  readonly position?: unknown;
  readonly normalized?: boolean;
  readonly output?: "f1" | "f2" | "f2-f1";
  readonly exact?: boolean;
  readonly octaves?: number;
  readonly lacunarity?: number;
  readonly gain?: number;
}

const NOISE_SALTS: Record<string, number> = {
  valueNoise: VALUE_SALT,
  perlinNoise: PERLIN_SALT,
  simplexNoise: SIMPLEX_SALT,
  worleyNoise: WORLEY_SALT,
};

const NOISE_LIB_FN: Record<string, string> = {
  valueNoise: "pcg_value_noise",
  perlinNoise: "pcg_perlin_noise",
  simplexNoise: "pcg_simplex_noise",
};

function noiseOpts(spec: Record<string, unknown>): NoiseOptsSpec {
  return (spec.opts ?? {}) as NoiseOptsSpec;
}

/**
 * Compile the position input of a noise fn (default: `position`) and
 * the frequency/offset transform into the noise-space sample point.
 * The transform is always emitted — the CPU computes `p * frequency +
 * offset` even at the defaults, which normalizes -0 to +0.
 */
function compileSamplePoint(fnName: string, spec: Record<string, unknown>, path: string, ctx: CompileCtx): Val {
  const opts = noiseOpts(spec);
  const posPath = opts.position === undefined ? path : `${path}.opts.position`;
  const pos =
    opts.position === undefined
      ? loadAttribute(ctx, path, "P", 3, `${fnName} position reads `)
      : compileArg(opts.position, posPath, ctx);
  if (pos.size !== 3) {
    throw new GpuCompileError(`${posPath}: ${fnName}: position field must have tupleSize 3, got ${pos.size}`);
  }
  const freq = wgslF32(opts.frequency ?? 1, `${path}.opts.frequency`);
  const [ox, oy, oz] = opts.offset ?? [0, 0, 0];
  const off = `vec3<f32>(${wgslF32(ox, `${path}.opts.offset`)}, ${wgslF32(oy, `${path}.opts.offset`)}, ${wgslF32(oz, `${path}.opts.offset`)})`;
  return ctx.emit(`${pos.ref} * ${freq} + ${off}`, 3);
}

/** Effective sampler seed, exactly as makeNoiseField derives it. */
function effectiveSeed(fnName: string, seed: number | undefined): number {
  return hash2(NOISE_SALTS[fnName], (seed ?? 0) >>> 0);
}

/** Wrap a raw noise value with the CPU normalize01 affine map. */
function emitNormalized(ctx: CompileCtx, raw: Val, range: NoiseRange, context: string): Val {
  const [lo, hi] = range;
  const span = hi - lo; // f64, as in normalize01
  return ctx.emit(`(${raw.ref} - ${wgslF32(lo, context)}) / ${wgslF32(span, context)}`, 1);
}

for (const fnName of ["valueNoise", "perlinNoise", "simplexNoise"] as const) {
  HANDLERS.set(fnName, (spec, path, ctx) => {
    const opts = noiseOpts(spec);
    const sp = compileSamplePoint(fnName, spec, path, ctx);
    ctx.libRoots.add(NOISE_LIB_FN[fnName]);
    const raw = ctx.emit(`${NOISE_LIB_FN[fnName]}(${wgslHexU32(effectiveSeed(fnName, opts.seed))}, ${sp.ref})`, 1);
    if (opts.normalized !== true) return raw;
    return emitNormalized(ctx, raw, NOISE_RAW_RANGES[fnName], `${path}.opts.normalized`);
  });
}

HANDLERS.set("worleyNoise", (spec, path, ctx) => {
  const opts = noiseOpts(spec);
  const output = opts.output ?? "f1";
  const exact = opts.exact === true;
  const sp = compileSamplePoint("worleyNoise", spec, path, ctx);
  ctx.libRoots.add("pcg_worley");
  const needsF2 = output !== "f1";
  const pair = ctx.emit(
    `pcg_worley(${wgslHexU32(effectiveSeed("worleyNoise", opts.seed))}, ${sp.ref}, ${exact}, ${needsF2})`,
    2,
  );
  const raw =
    output === "f1"
      ? ctx.emit(`${pair.ref}.x`, 1)
      : output === "f2"
        ? ctx.emit(`${pair.ref}.y`, 1)
        : ctx.emit(`${pair.ref}.y - ${pair.ref}.x`, 1);
  if (opts.normalized !== true) return raw;
  return emitNormalized(ctx, raw, NOISE_RAW_RANGES.worleyNoise[output], `${path}.opts.normalized`);
});

/** Raw output range of an fbm base factory (worley defaults to f1). */
function baseRawRange(base: string): NoiseRange {
  if (base === "worleyNoise") return NOISE_RAW_RANGES.worleyNoise.f1;
  return NOISE_RAW_RANGES[base as "valueNoise" | "perlinNoise" | "simplexNoise"];
}

/** Call expression for one fbm octave of the given base. */
function baseCall(base: string, seedExpr: string, posExpr: string): string {
  if (base === "worleyNoise") return `pcg_worley(${seedExpr}, ${posExpr}, false, false).x`;
  return `${NOISE_LIB_FN[base]}(${seedExpr}, ${posExpr})`;
}

HANDLERS.set("fbm", (spec, path, ctx) => {
  const base = spec.base as string;
  const opts = noiseOpts(spec);
  const octaves = opts.octaves ?? 4;
  const lacunarity = opts.lacunarity ?? 2;
  const gain = opts.gain ?? 0.5;
  const seed = opts.seed ?? 0;
  const frequency = opts.frequency ?? 1;
  const [ox, oy, oz] = opts.offset ?? [0, 0, 0];

  const posPath = opts.position === undefined ? path : `${path}.opts.position`;
  const pos =
    opts.position === undefined
      ? loadAttribute(ctx, path, "P", 3, "fbm position reads ")
      : compileArg(opts.position, posPath, ctx);
  if (pos.size !== 3) {
    throw new GpuCompileError(`${posPath}: fbm: position field must have tupleSize 3, got ${pos.size}`);
  }

  // Per-octave seed / frequency / amplitude chains, computed in f64
  // exactly as the CPU fbm does, then serialized as compile-time
  // constants; the summed output range follows the same accumulation.
  const range = baseRawRange(base);
  const seeds: string[] = [];
  const freqs: string[] = [];
  const amps: string[] = [];
  let amplitude = 1;
  let octaveFrequency = frequency;
  let lo = 0;
  let hi = 0;
  for (let o = 0; o < octaves; o++) {
    seeds.push(wgslHexU32(effectiveSeed(base, hashCombine(seed, o))));
    freqs.push(wgslF32(octaveFrequency, `${path}.opts.frequency`));
    amps.push(wgslF32(amplitude, `${path}.opts.gain`));
    lo += amplitude >= 0 ? amplitude * range[0] : amplitude * range[1];
    hi += amplitude >= 0 ? amplitude * range[1] : amplitude * range[0];
    amplitude *= gain;
    octaveFrequency *= lacunarity;
  }

  ctx.libRoots.add(base === "worleyNoise" ? "pcg_worley" : NOISE_LIB_FN[base]);
  const off = `vec3<f32>(${wgslF32(ox, `${path}.opts.offset`)}, ${wgslF32(oy, `${path}.opts.offset`)}, ${wgslF32(oz, `${path}.opts.offset`)})`;
  const body = `fn @NAME@(p: vec3<f32>) -> f32 {
  var seeds = array<u32, ${octaves}>(${seeds.join(", ")});
  var freqs = array<f32, ${octaves}>(${freqs.join(", ")});
  var amps = array<f32, ${octaves}>(${amps.join(", ")});
  var sum = 0f;
  for (var o = 0u; o < ${wgslU32(octaves)}; o++) {
    sum = sum + ${baseCall(base, "seeds[o]", "p * freqs[o] + " + off)} * amps[o];
  }
  return sum;
}`;
  const name = ctx.helper("fbm", body);
  const raw = ctx.emit(`${name}(${pos.ref})`, 1);
  if (opts.normalized !== true) return raw;
  if (!(hi > lo)) {
    // Unreachable through the JSON grammar (every base has a positive
    // raw span and octave 0 has amplitude 1), kept as a guard mirroring
    // the CPU fbm error.
    throw new GpuCompileError(
      `${path}: fbm: normalized: true needs a non-degenerate output range, got [${lo}, ${hi}] ` +
        "for this octaves/gain configuration",
    );
  }
  return emitNormalized(ctx, raw, [lo, hi], `${path}.opts.normalized`);
});

// ---------------------------------------------------------------------------
// attribute collection (pre-pass)

const NOISE_LIKE = new Set(["valueNoise", "perlinNoise", "simplexNoise", "worleyNoise", "fbm"]);

/**
 * Collect every attribute name the spec reads (position/noise imply "P").
 *
 * A `param` bound to a VALUE is inert here by construction: it has no
 * `args` and no `opts`, so the walk falls through it and adds nothing.
 * That is the saving — a named value costs a uniform slot and NOT one of
 * the seven usable storage-buffer slots, where carrying the same value in
 * an attribute column spends one per value.
 *
 * A `param` bound to a FIELD is not inert: the expression spliced there
 * is compiled into this kernel, so whatever it reads is read by this
 * kernel and has to be bound. Missing it would compile a body referencing
 * an unbound attribute — the one failure this pre-pass exists to make
 * impossible.
 */
function collectAttrNames(v: unknown, out: Set<string>): void {
  if (!isPlainObject(v)) return; // numbers and number arrays read nothing
  const fn = v.fn;
  if (fn === "param") {
    const bound = paramSpecOf(v as unknown as FieldSpec);
    if (bound !== undefined) collectAttrNames(bound, out);
    return;
  }
  if (fn === "attribute" || fn === "attributeIs") {
    if (typeof v.name === "string") out.add(v.name);
    return;
  }
  if (fn === "position") {
    out.add("P");
    return;
  }
  // randomField keys on point identity, so it reads P and `seed` even
  // though neither appears in its spec.
  if (fn === "randomField") {
    out.add("P");
    out.add("seed");
    return;
  }
  if (typeof fn === "string" && NOISE_LIKE.has(fn)) {
    const opts = v.opts;
    if (isPlainObject(opts) && opts.position !== undefined) {
      collectAttrNames(opts.position, out);
    } else {
      out.add("P");
    }
    return;
  }
  const args = v.args;
  if (Array.isArray(args)) {
    for (const a of args) collectAttrNames(a, out);
  }
}

// ---------------------------------------------------------------------------
// param collection (pre-pass)

/**
 * Uniform constant slots one FIELD kernel may carry — one per distinct
 * `param` name. Far above what an expression plausibly references (a slot
 * is 16 bytes of a uniform whose baseline binding limit is 64 KiB); the
 * cap exists so a pathological spec fails with a message naming the count
 * rather than building a uniform no device will bind.
 */
const MAX_FIELD_CONST_SLOTS = 16;

/**
 * Slot identity of an `attributeIs` pair, and its sort key. Both halves
 * go through `JSON.stringify`, which quotes and escapes them, so no
 * attribute name containing a comma or a quote can forge another pair's
 * key — the same guard the CPU constructor's field key uses.
 */
function attrIsKey(attr: string, value: string): string {
  return `${JSON.stringify(attr)},${JSON.stringify(value)}`;
}

/**
 * What a kernel carries in its uniform constant slots: the `param` names
 * with their arities first, then the `attributeIs` pairs. Two kinds of
 * slot in one array because they share one uniform tail, and appending
 * the new kind leaves every pre-existing kernel's slot numbering — and so
 * its key and its cached pipeline — exactly where it was.
 */
interface ParamPlan {
  /** Distinct names in SLOT ORDER: sorted, as the attribute pre-pass is. */
  readonly names: readonly string[];
  readonly slots: ReadonlyMap<string, number>;
  /** Components each slot holds — the binding's arity, 1 when unbound. */
  readonly arities: readonly number[];
  /** Distinct `attributeIs` pairs in SLOT ORDER, sorted, after the params. */
  readonly attrIs: readonly AttrIsSlot[];
  /** Slot index by {@link attrIsKey}; already offset past the param slots. */
  readonly attrIsSlots: ReadonlyMap<string, number>;
}

const EMPTY_PARAMS: ParamPlan = {
  names: [],
  slots: new Map(),
  arities: [],
  attrIs: [],
  attrIsSlots: new Map(),
};

/** Component count a recorded binding lowers as. */
function bindingArity(value: number | readonly number[]): number {
  return typeof value === "number" ? 1 : value.length;
}

/**
 * Walk `args` and `opts.position`, the two field-valued positions — plus
 * the expression spliced into a field-bound `param`, which is a third
 * one that lives beside the spec rather than inside it. It is walked for
 * the same reason the compiler descends into it: what it references is
 * referenced by the kernel, so a `param` nested inside a spliced field
 * must claim its slot and write its value like any other.
 */
function eachSpecNode(v: unknown, visit: (node: Record<string, unknown>) => void): void {
  if (!isPlainObject(v)) return;
  visit(v);
  if (v.fn === "param") {
    const bound = paramSpecOf(v as unknown as FieldSpec);
    if (bound !== undefined) eachSpecNode(bound, visit);
    return;
  }
  const args = v.args;
  if (Array.isArray(args)) {
    for (const a of args) eachSpecNode(a, visit);
  }
  const opts = v.opts;
  if (isPlainObject(opts)) eachSpecNode(opts.position, visit);
}

/**
 * Allocate a uniform slot per distinct `param` name, in sorted-name order
 * so codegen is deterministic exactly as the attribute pre-pass is.
 *
 * Arity is read from the binding recorded on each node (see
 * `attachParamValue`), and an UNBOUND node takes whatever arity a bound
 * node of the same name declared — never the other way round — so a
 * partially bound composition still lowers, and is then declined at
 * dispatch by {@link paramConstValues} rather than lowered wrong. Two
 * bound nodes disagreeing about arity is a genuine contradiction (one
 * slot cannot be both a scalar and a vec3) and rejects the compile.
 */
function planParams(root: FieldSpec): ParamPlan {
  const cached = PARAM_PLANS.get(root);
  if (cached !== undefined) return cached;
  // A contradiction is a property of the spec, so it is decided once and
  // remembered exactly as a plan is. The evaluator caches a compile
  // FAILURE in its kernel map for this reason; a plan failure happens
  // BEFORE a cache key can be computed, so without this the spec would be
  // re-walked and re-thrown every cook of a graph that is merely wrong.
  const failed = PARAM_PLAN_ERRORS.get(root);
  if (failed !== undefined) throw failed;
  try {
    const plan = computeParamPlan(root);
    PARAM_PLANS.set(root, plan);
    return plan;
  } catch (err) {
    if (err instanceof GpuCompileError) PARAM_PLAN_ERRORS.set(root, err);
    throw err;
  }
}

function computeParamPlan(root: FieldSpec): ParamPlan {
  const bound = new Map<string, number>();
  const seen = new Set<string>();
  // Distinct (attribute, literal) pairs, keyed so the map dedupes and the
  // key doubles as the sort key. Two references to one pair share a slot
  // for the same reason two references to one `param` name do: one index
  // is one index.
  const attrIs = new Map<string, AttrIsSlot>();
  eachSpecNode(root, (node) => {
    if (node.fn === "attributeIs") {
      // The grammar has already validated both halves for an authored
      // spec; a DERIVED one reaches here through the same registration,
      // so anything malformed is caught by `fieldFromJson` in
      // `compileFieldSpec` before codegen runs. Guarded anyway because
      // this pre-pass walks raw objects and a slot is not something to
      // reserve on a `undefined`.
      if (typeof node.name !== "string" || node.name === "") return;
      if (typeof node.value !== "string") return;
      attrIs.set(attrIsKey(node.name, node.value), { attr: node.name, value: node.value });
      return;
    }
    if (node.fn !== "param" || typeof node.name !== "string" || node.name === "") return;
    const name = node.name;
    // A name bound to a FIELD claims no slot: the expression is compiled
    // in place, so there is nothing for a uniform to carry.
    if (paramSpecOf(node as unknown as FieldSpec) !== undefined) return;
    // Bound to a field that cannot describe itself. `deviceSpec` already
    // declines an expression whose ROOT records one, so this catches the
    // other door: a spec COMPOSED over such an expression carries no
    // record of its own, and admitting it here would lower the reference
    // as an unbound uniform slot — a zero the CPU never produced, held
    // back today only by `paramConstValues` refusing to invent a payload.
    // Refused where the fact is known instead of relied on downstream.
    if (opaqueParam(node as unknown as FieldSpec)) {
      throw new GpuCompileError(
        `param ${JSON.stringify(name)} is bound to a Field that carries no spec (a makeField ` +
          "closure, or something composed over one), so there is nothing to compile in its place; " +
          "this expression evaluates on the CPU — build the bound field with the grammar " +
          "constructors or fieldFromJson if it should lower",
      );
    }
    seen.add(name);
    const value = paramValue(node as unknown as FieldSpec);
    if (value === undefined) return;
    const arity = bindingArity(value);
    if (arity > APPLY_CONST_COMPONENTS) {
      throw new GpuCompileError(
        `param ${JSON.stringify(name)} is bound to a ${arity}-tuple, but a uniform slot holds ` +
          `${APPLY_CONST_COMPONENTS} components; bind a tuple of 1 to ${APPLY_CONST_COMPONENTS}, ` +
          "or evaluate this field on the CPU",
      );
    }
    const previous = bound.get(name);
    if (previous !== undefined && previous !== arity) {
      throw new GpuCompileError(
        `param ${JSON.stringify(name)} is bound to a ${previous}-tuple in one place and a ` +
          `${arity}-tuple in another within the same expression; one uniform slot serves the name, ` +
          "so both references must have the same arity",
      );
    }
    bound.set(name, arity);
  });
  // One name, two lowerings, in one expression is LEGAL and lowers
  // correctly. It is reachable by composing separately built fields — a
  // knob bound to a field that was itself built with a binding of the
  // same name, which the shipped vocabulary invites by reusing `amount`,
  // `frequency` and `variant` across primitives — and the two references
  // are then genuinely different values in different scopes. Nothing has
  // to be reconciled: the lowering is decided PER NODE (a spliced node
  // compiles in place and never asks for a slot; a value-bound node
  // reads the slot this plan allocates), so the name in `slots` serves
  // exactly the references that need it.
  if (seen.size === 0 && attrIs.size === 0) return EMPTY_PARAMS;
  const names = [...seen].sort();
  // Sorted by the same composite key that identifies them, and numbered
  // AFTER the params: one total order over the slots, decided by the spec
  // alone, so the same spec always emits the same text.
  const attrIsKeys = [...attrIs.keys()].sort();
  const total = names.length + attrIsKeys.length;
  if (total > MAX_FIELD_CONST_SLOTS) {
    throw new GpuCompileError(
      `this field needs ${total} uniform constant slots (${names.length} distinct params and ` +
        `${attrIsKeys.length} distinct attributeIs literals), but a kernel carries at most ` +
        `${MAX_FIELD_CONST_SLOTS} (raise MAX_FIELD_CONST_SLOTS in compile.ts if an expression ` +
        "legitimately needs more)",
    );
  }
  return {
    names,
    slots: new Map(names.map((n, i) => [n, i])),
    arities: names.map((n) => bound.get(n) ?? 1),
    attrIs: attrIsKeys.map((k) => attrIs.get(k) as AttrIsSlot),
    attrIsSlots: new Map(attrIsKeys.map((k, i) => [k, names.length + i])),
  };
}

/** Plans, plan failures and keys memoized per spec OBJECT; specs are immutable by contract. */
const PARAM_PLANS = new WeakMap<FieldSpec, ParamPlan>();
const PARAM_PLAN_ERRORS = new WeakMap<FieldSpec, GpuCompileError>();
const SPEC_KEYS = new WeakMap<FieldSpec, string>();

/**
 * The slots' contribution to a specialization key: for a `param`, its
 * name and arity and never its value; for an `attributeIs`, the pair
 * whose INDEX the slot will hold and never that index. Both kinds are
 * counted because both decide the emitted text — the slot numbering, the
 * struct's array length, and so the uniform size — and a key that
 * described only half the slots would name a kernel that is not the one
 * compiled.
 *
 * Emitted only for the kinds actually present, so a param-free kernel's
 * key is character for character what it was before either kind existed.
 */
function paramSig(plan: ParamPlan): string {
  let sig = "";
  if (plan.names.length > 0) {
    sig += `|params=[${plan.names.map((n, i) => `${JSON.stringify(n)}:${plan.arities[i]}`).join(",")}]`;
  }
  if (plan.attrIs.length > 0) {
    sig += `|attrIs=[${plan.attrIs.map((a) => attrIsKey(a.attr, a.value)).join(";")}]`;
  }
  return sig;
}

/**
 * The VALUE-FREE specialization identity of a spec: the structural key of
 * the field it builds with NOTHING bound, plus the params' names and
 * arities. This is the key a kernel cache must use.
 *
 * The distinction matters because there are deliberately two keys. A
 * BOUND field's `key` carries the value — that is the CPU memoization
 * contract, and what makes rebinding invalidate exactly the nodes that
 * read the name. The kernel is the same kernel for every value, so a
 * cache keyed on the field's key would gain an entry per slider tick of
 * an unbounded Map. Crossing the two the other way would be worse: GPU
 * bytes served under a CPU key.
 *
 * `fieldKey` is the key of the field this spec came from, and is the
 * ANSWER whenever the spec references no param: a field's key and its
 * spec's key are the same string (that equality is what the derived-spec
 * round-trip pins), and with no param in it there is no value in it
 * either. So the overwhelmingly common case costs one walk and returns
 * exactly the key that shipped, and only a spec that actually names a
 * param pays to rebuild itself unbound.
 *
 * A FIELD binding sits on the other side of that line, and has to: the
 * expression spliced in is compiled in place, so it decides the emitted
 * text and belongs to the kernel's identity. It gets there by the same
 * two routes — the rebuild below descends into it (`fieldFromJson`
 * consults the spliced spec when nothing is bound), and the shortcut
 * above returns `fieldKey`, which carries the bound field's key by
 * composition. So two values of a number share a kernel while two
 * different bound EXPRESSIONS do not, which is exactly the WGSL they
 * generate.
 *
 * Memoized on the spec object, which callers treat as immutable
 * (`peekFieldSpec`'s contract); a different value means a different
 * `fieldFromJson` call and so a different spec object, whose key then
 * comes out IDENTICAL and hits the same kernel.
 *
 * The rebuild is `fieldFromJsonValueFree` rather than `fieldFromJson`
 * because a value written INSIDE the node (`{fn: "param", name, value}`)
 * would otherwise be read back by it — the one kind of bound value a
 * value-free rebuild does not shed on its own. See that function.
 */
export function specKernelKey(spec: FieldSpec, fieldKey: string): string {
  const plan = planParams(spec);
  if (plan.names.length === 0 && plan.attrIs.length === 0) return fieldKey;
  const cached = SPEC_KEYS.get(spec);
  if (cached !== undefined) return cached;
  const key = `${fieldFromJsonValueFree(spec).key}${paramSig(plan)}`;
  SPEC_KEYS.set(spec, key);
  return key;
}

/** {@link paramConstValues}' two outcomes: the slot payload, or why there is none. */
export type ParamConstValues =
  | { readonly values: readonly number[] }
  | { readonly problem: string };

function sameComponents(a: readonly number[], b: readonly number[]): boolean {
  return a.length === b.length && a.every((v, i) => Object.is(v, b[i]));
}

/**
 * The uniform payload for a compiled kernel's constant slots:
 * {@link APPLY_CONST_COMPONENTS} f32 per slot (zero-padded), in slot
 * order — or the reason the spec's bindings cannot produce one.
 *
 * Read from the SPEC, never from the kernel: the kernel is shared by
 * every value the names are bound to, which is the point of the uniform.
 * Values are passed through as authored, because a JS number written
 * through a `Float32Array` rounds exactly as the CPU `constant` column it
 * substitutes for — including `-0` and subnormals, which is where this
 * path is strictly closer to the reference than a baked literal.
 *
 * The two refusals are the cases where GPU bytes would silently differ
 * from CPU bytes: a reference nothing bound (the CPU field throws, so the
 * device must decline and let it), and two references to one name bound
 * to different values in one expression, which one slot cannot represent.
 *
 * A reference bound to a FIELD is skipped: it holds no slot to fill, the
 * expression having been compiled in place.
 */
export function paramConstValues(spec: FieldSpecArg, kernel: CompiledFieldKernel): ParamConstValues {
  if (kernel.constSlots === 0) return { values: [] };
  // A kernel carrying an `attributeIs` slot cannot be filled from the
  // spec, and saying so HERE is what makes every spec-only caller decline
  // instead of writing a payload one slot short. The literal's slot holds
  // its index in a particular geometry's string table, and this function
  // is handed no geometry — deliberately, because the plan-time caller
  // that relies on it (`run.ts`, which bakes the payload into a fused
  // step before any geometry exists) has none to hand it.
  // {@link constSlotValues} is the door that does.
  if (kernel.attrIsSlots.length > 0) {
    return {
      problem:
        `this kernel carries ${kernel.attrIsSlots.length} attributeIs slot(s) ` +
        `(${kernel.attrIsSlots.map((a) => `${JSON.stringify(a.attr)} == ${JSON.stringify(a.value)}`).join(", ")}) ` +
        "whose values are string-table indices of the geometry being cooked; fill them with " +
        "constSlotValues, which takes that geometry's attribute set",
    };
  }
  return paramSlotValues(spec, kernel);
}

/** The `param` half of the payload: {@link kernel.paramNames} in slot order. */
function paramSlotValues(spec: FieldSpecArg, kernel: CompiledFieldKernel): ParamConstValues {
  const byName = new Map<string, readonly number[]>();
  let problem: string | undefined;
  eachSpecNode(spec, (node) => {
    if (node.fn !== "param" || typeof node.name !== "string" || node.name === "") return;
    const name = node.name;
    if (paramSpecOf(node as unknown as FieldSpec) !== undefined) return;
    const value = paramValue(node as unknown as FieldSpec);
    if (value === undefined) {
      problem ??= `param ${JSON.stringify(name)} has no bound value`;
      return;
    }
    const components = typeof value === "number" ? [value] : [...value];
    const previous = byName.get(name);
    if (previous === undefined) byName.set(name, components);
    else if (!sameComponents(previous, components)) {
      problem ??= `param ${JSON.stringify(name)} is bound to two different values in one expression`;
    }
  });
  if (problem !== undefined) return { problem };
  const values: number[] = [];
  for (const name of kernel.paramNames) {
    const components = byName.get(name);
    if (components === undefined) {
      // Only reachable if a caller pairs a kernel with a spec it was not
      // compiled from; refusing beats writing a zero the CPU never saw.
      return { problem: `param ${JSON.stringify(name)} is not referenced by this spec` };
    }
    for (let k = 0; k < APPLY_CONST_COMPONENTS; k++) {
      values.push(k < components.length ? components[k] : 0);
    }
  }
  return { values };
}

/**
 * The slot index written for a literal the geometry's string table does
 * not hold. No table index can equal it (they are 0-based and dense), so
 * every lane compares false and the column is the zeros the CPU produces
 * for the same absent literal. The lane is f32 and -1 is exact there, so
 * nothing rounds.
 */
const ABSENT_STRING_INDEX = -1;

/**
 * The read-only slice of an attribute set a geometry-aware fill needs:
 * find a column, ask its type, ask its table for an index. Structural on
 * purpose — this module is codegen and imports no data types — and
 * `AttributeSet` satisfies it as it stands.
 *
 * `lookupString` and not `internString`: the inserting one would append
 * the literal to a table it is only reading, which is invisible until the
 * next `copyFrom` compacts that table and renumbers everything after it.
 * Resolving a field must not edit the geometry it resolves over.
 */
export interface StringTableSource {
  get(name: string):
    | { readonly type: string; lookupString(value: string): number | undefined }
    | undefined;
}

/**
 * The full uniform payload for a kernel's constant slots, resolved
 * against the geometry being cooked: the `param` values exactly as
 * {@link paramConstValues} reads them, then one string-table index per
 * `attributeIs` slot.
 *
 * This is the geometry-aware counterpart, and the reason there are two:
 * a param's value is a property of the SPEC and can be read whenever the
 * spec is in hand, while an `attributeIs` slot holds an index into a
 * table that belongs to one geometry. Resolving it at compile time would
 * bake a geometry's private numbering into a kernel the cache shares
 * across geometries — see the handler. So it is resolved here, per
 * dispatch, where the geometry is.
 */
export function constSlotValues(
  spec: FieldSpecArg,
  kernel: CompiledFieldKernel,
  attrs: StringTableSource,
): ParamConstValues {
  if (kernel.constSlots === 0) return { values: [] };
  const params = paramSlotValues(spec, kernel);
  if ("problem" in params) return params;
  if (kernel.attrIsSlots.length === 0) return params;
  const values = [...params.values];
  for (const slot of kernel.attrIsSlots) {
    const attr = attrs.get(slot.attr);
    if (attr === undefined || attr.type !== "string") {
      // Unreachable through the evaluator, which compiles the kernel
      // against the very attribute set it then fills from — a missing or
      // numeric column threw in `resolveStringAttr` and there is no
      // kernel to fill. Refused rather than filled with a zero, which is
      // a REAL index (the table's default entry) and would silently mark
      // every untouched element as a match.
      return {
        problem:
          `attributeIs ${JSON.stringify(slot.attr)}: this geometry has no string attribute of ` +
          `that name (${attr === undefined ? "no such attribute" : `it is ${attr.type}`}), so the ` +
          "literal has no index to resolve to",
      };
    }
    // Absent is data, not an error: a cell holding no pines legitimately
    // has no "pine" in its table, and throwing would make the result
    // depend on how the world was partitioned. See the CPU constructor.
    const index = attr.lookupString(slot.value) ?? ABSENT_STRING_INDEX;
    for (let k = 0; k < APPLY_CONST_COMPONENTS; k++) values.push(k === 0 ? index : 0);
  }
  return { values };
}

// ---------------------------------------------------------------------------
// layout validation and kernel assembly

const VALID_ATTR_TYPES = new Set(["f32", "i32", "u32", "bool", "string"]);

function validateLayout(layout: FieldKernelLayout): void {
  if (!isPlainObject(layout) || !isPlainObject(layout.attributes)) {
    throw new GpuCompileError(
      "compileFieldSpec: layout must be { attributes: { name: { type, tupleSize } } }",
    );
  }
  for (const [name, attr] of Object.entries(layout.attributes)) {
    if (!isPlainObject(attr) || !VALID_ATTR_TYPES.has(attr.type as string)) {
      throw new GpuCompileError(
        `kernel layout attribute ${JSON.stringify(name)}: unknown type ${JSON.stringify(
          (attr as { type?: unknown })?.type,
        )}; valid types: "f32", "i32", "u32", "bool", "string" (a string column binds as u32 and is readable only through attributeIs)`,
      );
    }
    const ts = (attr as { tupleSize?: unknown }).tupleSize;
    if (typeof ts !== "number" || !Number.isInteger(ts) || ts < 1) {
      throw new GpuCompileError(
        `kernel layout attribute ${JSON.stringify(name)}: tupleSize must be a positive integer, got ${String(ts)}`,
      );
    }
  }
}

function normalizeRootSpec(spec: FieldSpecArg): FieldSpec {
  if (typeof spec === "number") return { fn: "constant", value: spec };
  if (Array.isArray(spec)) return { fn: "constant", value: [...(spec as readonly number[])] };
  return spec as FieldSpec;
}

/**
 * Storage buffer element type an attribute binds as. `bool` binds as u32
 * because the CPU stores it in a `Uint8Array` the marshaller widens;
 * `string` binds as u32 because that is already what it IS — a string
 * column is a `Uint32Array` of table indices, which is exactly what
 * `attributeIs` compares. Nothing about the table crosses to the device.
 */
function bufferType(attr: FieldKernelAttr): GpuScalarType {
  return attr.type === "bool" || attr.type === "string" ? "u32" : (attr.type as GpuScalarType);
}

/**
 * Compile a field spec to a WGSL compute kernel specialized to the
 * given layout. See the module doc for the semantics contract. Throws
 * `FieldJsonError` for malformed specs (shared validator) and
 * {@link GpuCompileError} for GPU-specific constraints (unknown fn,
 * missing/string attribute, tuple sizes above 4).
 */
export function compileFieldSpec(spec: FieldSpecArg, layout: FieldKernelLayout): CompiledFieldKernel {
  validateLayout(layout);
  const rootSpec = normalizeRootSpec(spec);
  // Full grammar validation plus the canonical structural key (spec JSON
  // key order and defaulted options do not affect it). Built with NO
  // bindings AND with inline values ignored, so a `param` contributes
  // `param("name")` and the key stays value-free — see `specKernelKey`.
  // This key becomes `CompiledFieldKernel.key`, which `run.ts` keys its
  // unbounded pipeline map on, so a value leaking into it is a pipeline
  // per knob position and not merely a duplicated string.
  const field = fieldFromJsonValueFree(rootSpec);

  // Pre-pass: find every attribute the spec reads and pre-assign binding
  // slots (sorted by name) so codegen is single-pass and deterministic.
  //
  // String columns are eligible since `attributeIs` — the one fn that
  // reads one — and are filtered no further than any other type: a name
  // reached ONLY through `attribute` is still refused, by the handler,
  // where the message can say what to write instead. Filtering it out
  // here would trade that message for "not in the kernel layout", which
  // is not true and not actionable.
  const attrNames = new Set<string>();
  collectAttrNames(rootSpec, attrNames);
  const eligible = [...attrNames].filter((n) => Object.hasOwn(layout.attributes, n)).sort();
  // The same pre-pass for params, over the other resource a spec claims:
  // a uniform slot per distinct name, sorted the same way.
  const params = planParams(rootSpec);
  const ctx = new CompileCtx(layout, eligible, params);

  // Root special cases mirror the CPU output column types: index → u32,
  // i32/u32 attributes → their own type; everything else lands as f32.
  let outType: GpuScalarType = "f32";
  let outTupleSize = 0;
  const storeLines: string[] = [];
  const storeExpression = (root: Val): void => {
    outTupleSize = root.size;
    if (root.size === 1) {
      storeLines.push(`  outBuf[i] = ${root.ref};`);
    } else {
      for (let k = 0; k < root.size; k++) {
        storeLines.push(`  outBuf[${flatIndex(root.size, k)}] = ${root.ref}.${XYZW[k]};`);
      }
    }
  };
  const rootAttrName =
    rootSpec.fn === "attribute" ? (rootSpec.name as string) : rootSpec.fn === "position" ? "P" : undefined;
  if (rootSpec.fn === "index") {
    outType = "u32";
    outTupleSize = 1;
    storeLines.push("  outBuf[i] = i;");
  } else if (rootAttrName !== undefined) {
    const expect = rootSpec.fn === "position" ? 3 : (rootSpec.tupleSize as number | undefined);
    const origin = rootSpec.fn === "position" ? "position reads " : "";
    const attr = resolveLayoutAttr(ctx, "$", rootAttrName, expect, origin);
    if (attr.type === "i32" || attr.type === "u32") {
      // Raw integer copy, preserving the CPU zero-copy column type.
      outType = attr.type;
      outTupleSize = attr.tupleSize;
      const b = ctx.binding(rootAttrName);
      for (let k = 0; k < attr.tupleSize; k++) {
        storeLines.push(`  outBuf[${flatIndex(attr.tupleSize, k)}] = ${b.varName}[${flatIndex(attr.tupleSize, k)}];`);
      }
    } else {
      // f32 and bool attributes read as f32 columns on CPU too.
      storeExpression(compileNode(rootSpec as unknown as Record<string, unknown>, "$", ctx));
    }
  } else {
    storeExpression(compileNode(rootSpec as unknown as Record<string, unknown>, "$", ctx));
  }

  const bound = ctx.boundAttrs();
  const inputs: KernelInput[] = bound.map((b) => ({
    name: b.name,
    type: bufferType(b.attr),
    tupleSize: b.attr.tupleSize,
    binding: b.binding,
  }));
  const outputBinding = bound.length + 1;

  const decls: string[] = [`@group(0) @binding(0) var<uniform> params: PcgParams;`];
  for (const b of bound) {
    decls.push(
      `@group(0) @binding(${b.binding}) var<storage, read> ${b.varName}: array<${bufferType(b.attr)}>; ` +
        `// attribute ${JSON.stringify(b.name)}: ${b.attr.type} tupleSize ${b.attr.tupleSize}`,
    );
  }
  decls.push(`@group(0) @binding(${outputBinding}) var<storage, read_write> outBuf: array<${outType}>;`);

  // The constant tail is byte-for-byte the apply kernels' (`_pad0` brings
  // the 12-byte scalar header up to the 16-byte alignment `array<vec4>`
  // requires in the uniform address space), so both kinds of step write
  // their slots through the same offset. A spec with no params emits the
  // header alone — character for character what it emitted before params
  // existed, which is what lets every pre-existing kernel keep its key.
  const constSlots = params.names.length + params.attrIs.length;
  const constMembers =
    constSlots === 0 ? "" : `\n  _pad0: u32,\n  consts: array<vec4<f32>, ${constSlots}>,`;
  const blocks: string[] = [
    `// Generated by pcg-ts compileFieldSpec (WGSL field kernel).
// Dispatch: 1D, chunked; each chunk runs ceil(chunkElements / ${WORKGROUP_SIZE}) workgroups of ${WORKGROUP_SIZE}
// with element index i = chunkOffset + gid.x; one invocation per element.

struct PcgParams {
  count: u32,
  seed: u32,
  chunkOffset: u32,${constMembers}
}

${decls.join("\n")}`,
    ...libClosure(ctx.libRoots),
    ...ctx.helperBlocks(),
    `@compute @workgroup_size(${WORKGROUP_SIZE})
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
  let i = gid.x + params.chunkOffset;
  if (i >= params.count) {
    return;
  }
${[...ctx.lines, ...storeLines].join("\n")}
}`,
  ];

  const layoutKey = bound
    .map((b) => `${JSON.stringify(b.name)}:${b.attr.type}x${b.attr.tupleSize}`)
    .join(",");
  const specKey = `${field.key}${paramSig(params)}`;
  // Seed the memo the evaluator reads before it decides to compile at
  // all, so the two spellings of this key cannot drift apart.
  SPEC_KEYS.set(rootSpec, specKey);
  return {
    wgsl: `${blocks.join("\n\n")}\n`,
    entryPoint: "main",
    workgroupSize: WORKGROUP_SIZE,
    outTupleSize,
    outType,
    inputs,
    bindings: { uniforms: 0, output: outputBinding },
    constSlots,
    paramNames: params.names,
    attrIsSlots: params.attrIs,
    uniformBytes: applyUniformBytes(constSlots),
    usesSeed: ctx.usesSeed,
    key: `${CODEGEN_VERSION}|spec=${specKey}|layout=[${layoutKey}]`,
  };
}
